// data.jsx - Member data for Evergreen Apartment portal.
// Updated from uploads/Members all Details - Copy (1).xlsx.

const SOCIETY = {
  name: "Evergreen Apartment",
  tagline: "A Cooperative Group Housing Society",
  est: "1998",
  location: "Plot 9, Sector 7, Dwarka, New Delhi — 110075",
  regNo: "Regd. No. 837",
  pan: "AAATE0837F",
  blocks: 1,
  flats: 165,
  floors: 4,
  area: "2.6 acres",
  email: "evergreensocietyplot9@gmail.com",
  phone: "011-42441492",
  domain: "evergreen-dwarka.in",
};

const MEMBERS = [
  {
    "id": "EA-0001",
    "sn": 1,
    "flat": 1,
    "membership": "176",
    "name": "MR. P.S. SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "gaurdevesh13@gmail.com",
    "phone": "9350255597(NUB. OF GRANDSON)",
    "alternatePhone": null,
    "parking": "P-001",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "4 days ago",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0002",
    "sn": 2,
    "flat": 2,
    "membership": null,
    "name": "MRS. MADHUBALA SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9654110527",
    "alternatePhone": null,
    "parking": "P-002",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0003",
    "sn": 3,
    "flat": 3,
    "membership": null,
    "name": "Ms. Shobha Singh",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "drabhishek.gupta1995@gmail.com",
    "phone": "9701026379",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CBE1770"
  },
  {
    "id": "EA-0004",
    "sn": 4,
    "flat": 4,
    "membership": null,
    "name": "MR. J.K. Batra",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "Rakeshbatra7@gamil.com",
    "phone": "9540493030",
    "alternatePhone": null,
    "parking": "P-004",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "4 days ago",
    "committee": null,
    "vehicleNumber": "UP32ME 7903"
  },
  {
    "id": "EA-0005",
    "sn": 5,
    "flat": 5,
    "membership": null,
    "name": "MR. A.K. Singh",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "amaresh1602@gmail.com",
    "phone": "8826544665/9953318110",
    "alternatePhone": null,
    "parking": "P-005",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL10CR 3018"
  },
  {
    "id": "EA-0006",
    "sn": 6,
    "flat": 6,
    "membership": null,
    "name": "SMT. MAYA DEVI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9212717354",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAC 3309/MH43BU8307"
  },
  {
    "id": "EA-0007",
    "sn": 7,
    "flat": 7,
    "membership": "361",
    "name": "Mrs SHEELA DEVI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "gaurimitansh@gmail.com",
    "phone": "9810744307/8076679108",
    "alternatePhone": null,
    "parking": "P-007",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "4 days ago",
    "committee": null,
    "vehicleNumber": "DL9CAU 1033"
  },
  {
    "id": "EA-0008",
    "sn": 8,
    "flat": 8,
    "membership": "340",
    "name": "MR. KULWANT SINGH",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "kldpsingh27@yahoo.in",
    "phone": "9910057429",
    "alternatePhone": null,
    "parking": "P-008",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL3CCR 1023"
  },
  {
    "id": "EA-0009",
    "sn": 9,
    "flat": 9,
    "membership": "287",
    "name": "MS. KOMAL SEAL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "7668896321",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL1CV 6567"
  },
  {
    "id": "EA-0010",
    "sn": 10,
    "flat": 10,
    "membership": "378",
    "name": "SMT.CHANDER KANTA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "mlchawla1950@gmail.com",
    "phone": "9818232596/9277395238",
    "alternatePhone": null,
    "parking": "P-010",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "4 days ago",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0011",
    "sn": 11,
    "flat": 11,
    "membership": "344",
    "name": "SMT. SHIVANI SABHARWAL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "shivanisabharwal1973@gmail.com",
    "phone": "9582925865",
    "alternatePhone": null,
    "parking": "P-011",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CBF0424"
  },
  {
    "id": "EA-0012",
    "sn": 12,
    "flat": 12,
    "membership": "298",
    "name": "MR. AMAR SINGH HADA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9868072021",
    "alternatePhone": null,
    "parking": "P-012",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL3CBA5096"
  },
  {
    "id": "EA-0013",
    "sn": 13,
    "flat": 13,
    "membership": "415",
    "name": "MR.NARESH K VERMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "vermanaresh63@gmail.com",
    "phone": "9650768153/9891748276",
    "alternatePhone": null,
    "parking": "P-013",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "4 days ago",
    "committee": null,
    "vehicleNumber": "DL1CS 9602/ DL12CU8616"
  },
  {
    "id": "EA-0014",
    "sn": 14,
    "flat": 14,
    "membership": "375",
    "name": "MR. H.M. SRIVASTAVA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "srivastavarti@rediffmail.com",
    "phone": "9818556615/8585985071",
    "alternatePhone": null,
    "parking": "P-014",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": "DL10CP 0932"
  },
  {
    "id": "EA-0015",
    "sn": 15,
    "flat": 15,
    "membership": "178",
    "name": "MR. V. CHANDRAMAULI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "khreda2925@gmail.com",
    "phone": "9810009083",
    "alternatePhone": null,
    "parking": "P-015",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL12CG 4955"
  },
  {
    "id": "EA-0016",
    "sn": 16,
    "flat": 16,
    "membership": "354",
    "name": "MRS. RADHA SUBRAMANIAM",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "rasubu@gmail.com",
    "phone": "9810054024/995332214",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL3CBU 6545"
  },
  {
    "id": "EA-0017",
    "sn": 17,
    "flat": 17,
    "membership": "318",
    "name": "MRS. ARUN LATA SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "Arunlata324@gmail.com",
    "phone": "8802090311/9868146537",
    "alternatePhone": null,
    "parking": "P-017",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": "DL1CAE 2864"
  },
  {
    "id": "EA-0018",
    "sn": 18,
    "flat": 18,
    "membership": "342",
    "name": "MR. J.K. JAIN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "jkjain322@yahoo.com",
    "phone": "9811870381",
    "alternatePhone": null,
    "parking": "P-018",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0019",
    "sn": 19,
    "flat": 19,
    "membership": "410",
    "name": "MR. SANTANU SAHA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "8017107922/9899994374",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL10CJ 7564"
  },
  {
    "id": "EA-0020",
    "sn": 20,
    "flat": 20,
    "membership": "243",
    "name": "MRS. VANDANA KOHLI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "sonia.minishka@gmail.com",
    "phone": "9891456784",
    "alternatePhone": null,
    "parking": "P-020",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": "OR02BL 7302"
  },
  {
    "id": "EA-0021",
    "sn": 21,
    "flat": 21,
    "membership": "393",
    "name": "MRS ANUPAMA SINGH",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "brsingh60@gmail.com",
    "phone": "9431347679/7070611147",
    "alternatePhone": null,
    "parking": "P-021",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "MH12SU0893"
  },
  {
    "id": "EA-0022",
    "sn": 22,
    "flat": 22,
    "membership": "390",
    "name": "MR. DORI LAL & SMT. SHASHI BALA",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 0,
    "email": "d_lal64@yahoo.com",
    "phone": "9968092478",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "PB10GB 2949"
  },
  {
    "id": "EA-0023",
    "sn": 23,
    "flat": 23,
    "membership": null,
    "name": "MRS NEELAM B CHADHA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9718484502/8587090552",
    "alternatePhone": null,
    "parking": "P-023",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": "CH01AE7965"
  },
  {
    "id": "EA-0024",
    "sn": 24,
    "flat": 24,
    "membership": "370",
    "name": "MRS. SUDHA KARAN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9810218883",
    "alternatePhone": null,
    "parking": "P-024",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL10CP 9594"
  },
  {
    "id": "EA-0025",
    "sn": 25,
    "flat": 25,
    "membership": "391",
    "name": "MR. MANISH NEGI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9811157876",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAG 2567"
  },
  {
    "id": "EA-0026",
    "sn": 26,
    "flat": 26,
    "membership": "304",
    "name": "MR. ANIL JOSHI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9811979814",
    "alternatePhone": null,
    "parking": "P-026",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0027",
    "sn": 27,
    "flat": 27,
    "membership": null,
    "name": "MR. ASHWANI & MRS. RACHANA CHAUDRY",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 0,
    "email": null,
    "phone": "7798014611",
    "alternatePhone": null,
    "parking": "P-027",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "MH12QT 7784"
  },
  {
    "id": "EA-0028",
    "sn": 28,
    "flat": 28,
    "membership": "334",
    "name": "MR. KULDIP SINGH",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "kldpsingh27@yahoo.in",
    "phone": "9910057429/9810209853",
    "alternatePhone": null,
    "parking": "P-028",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0029",
    "sn": 29,
    "flat": 29,
    "membership": "182",
    "name": "MR. MANISH JAIN & MRS. SUNITA JAIN",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 0,
    "email": null,
    "phone": "9310990003",
    "alternatePhone": "+91 97013• ••214",
    "parking": "P-029",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": "DL9CAY 4651/DL8CNB 7227"
  },
  {
    "id": "EA-0030",
    "sn": 30,
    "flat": 30,
    "membership": null,
    "name": "MR. S.K. GUPTA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9899503101",
    "alternatePhone": null,
    "parking": "P-030",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 days ago",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0031",
    "sn": 31,
    "flat": 31,
    "membership": "60",
    "name": "MR. RAJESH KAURA & SMT. POOJA KAURA",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 0,
    "email": null,
    "phone": "8800125966/9810403236",
    "alternatePhone": null,
    "parking": "P-031",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL4CAP 7372"
  },
  {
    "id": "EA-0032",
    "sn": 32,
    "flat": 32,
    "membership": "394",
    "name": "MR.VINOD KUMAR",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": null,
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "No phone",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0033",
    "sn": 33,
    "flat": 33,
    "membership": "308",
    "name": "MS. UMANG DAWRA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "umgangel@gmail.com",
    "phone": "9654550809",
    "alternatePhone": null,
    "parking": "P-033",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 days ago",
    "committee": null,
    "vehicleNumber": "UP78EW 2424"
  },
  {
    "id": "EA-0034",
    "sn": 34,
    "flat": 34,
    "membership": "321",
    "name": "MRS.SUGANTHI RAJARAM",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "suganthi.rajaram112@gmail.com",
    "phone": "9811613130",
    "alternatePhone": null,
    "parking": "P-034",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL10CR 3031"
  },
  {
    "id": "EA-0035",
    "sn": 35,
    "flat": 35,
    "membership": "376",
    "name": "MRS. M. KAUSHIK",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9313564221",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAW 6592"
  },
  {
    "id": "EA-0036",
    "sn": 36,
    "flat": 36,
    "membership": "170",
    "name": "MR. DEEPAKA KARAN & MRS, REEMA KARAN",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 0,
    "email": null,
    "phone": "8448467748/9999103078",
    "alternatePhone": null,
    "parking": "P-036",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 days ago",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0037",
    "sn": 37,
    "flat": 37,
    "membership": "416",
    "name": "SMT. ALKA SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9643808587/9310074622",
    "alternatePhone": null,
    "parking": "P-037",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL3CCM 1200"
  },
  {
    "id": "EA-0038",
    "sn": 38,
    "flat": 38,
    "membership": "374",
    "name": "MR .MUKESH KHURANA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9899591521",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CBE7182"
  },
  {
    "id": "EA-0039",
    "sn": 39,
    "flat": 39,
    "membership": "235",
    "name": "MRS. SAROJ B SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "9899017115/9582245722",
    "alternatePhone": null,
    "parking": "P-039",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 days ago",
    "committee": null,
    "vehicleNumber": "DL9CAS 5088"
  },
  {
    "id": "EA-0040",
    "sn": 40,
    "flat": 40,
    "membership": null,
    "name": "MR. SANDEEP BHARDWAJ",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": null,
    "phone": "(jishnu bhardwaj)9873947113",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAL 7363/ DL8CQ 9542"
  },
  {
    "id": "EA-0041",
    "sn": 41,
    "flat": 41,
    "membership": "208",
    "name": "MR. S.K. GUPTA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "skgupta.qc@gmail.com",
    "phone": "9810546772",
    "alternatePhone": null,
    "parking": "P-041",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL3CCL 5300/ DL12CD 4600"
  },
  {
    "id": "EA-0042",
    "sn": 42,
    "flat": 42,
    "membership": "372",
    "name": "MR. BHANU PRAKASH",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 0,
    "email": "bhanu_prakash62@gmail.com",
    "phone": "9818290616",
    "alternatePhone": "+91 97016• ••217",
    "parking": "P-042",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 days ago",
    "committee": null,
    "vehicleNumber": "DL9CAM 0249"
  },
  {
    "id": "EA-0043",
    "sn": 43,
    "flat": 43,
    "membership": "382",
    "name": "MR. NARESH BHARADWAJ",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "9868161144/9013136660",
    "alternatePhone": null,
    "parking": "P-043",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 weeks ago",
    "committee": null,
    "vehicleNumber": "DL9CAP 0209"
  },
  {
    "id": "EA-0044",
    "sn": 44,
    "flat": 44,
    "membership": "232",
    "name": "MR.GYANENDAR SINGH SIROHI AND SAROJ SIROHI",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 1,
    "email": "rahulsirohi91@gmail.com",
    "phone": "9818060259/9910816608",
    "alternatePhone": null,
    "parking": "P-044",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAS 2057/DL8CAT 9191/DL9CAY 5663"
  },
  {
    "id": "EA-0045",
    "sn": 45,
    "flat": 45,
    "membership": null,
    "name": "MRS. V. MUTHUSWAMY",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "9910135488",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0046",
    "sn": 46,
    "flat": 46,
    "membership": "183",
    "name": "MRS.INDU CHIKARA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "rajschhikara@yahoo.com",
    "phone": "8010531622",
    "alternatePhone": null,
    "parking": "P-046",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 weeks ago",
    "committee": null,
    "vehicleNumber": "PB02EP 7859"
  },
  {
    "id": "EA-0047",
    "sn": 47,
    "flat": 47,
    "membership": "139",
    "name": "MR. D.C. RABHA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "9211367760",
    "alternatePhone": null,
    "parking": "P-047",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0048",
    "sn": 48,
    "flat": 48,
    "membership": "405",
    "name": "MR.RAKESH KUMAR & SMT. GEETA SHARMA",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 1,
    "email": "rakeshdevgan2001@yahoo.co.in",
    "phone": "9958535385/8447635382",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAR 5970"
  },
  {
    "id": "EA-0049",
    "sn": 49,
    "flat": 49,
    "membership": null,
    "name": "MRS. ANUPAMA SHARMA & MR LOKESH KUMAR SHARMA",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 1,
    "email": null,
    "phone": "9958833441",
    "alternatePhone": null,
    "parking": "P-049",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 weeks ago",
    "committee": null,
    "vehicleNumber": "DL9CAS 0787/DL10CV7466"
  },
  {
    "id": "EA-0050",
    "sn": 50,
    "flat": 50,
    "membership": "220",
    "name": "MRS. HARINDER GILL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "gillhar@gmail.com",
    "phone": "9999460026/9999471518",
    "alternatePhone": null,
    "parking": "P-050",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CBB 7387"
  },
  {
    "id": "EA-0051",
    "sn": 51,
    "flat": 51,
    "membership": "300",
    "name": "MR. R.K. SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "8178799485",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0052",
    "sn": 52,
    "flat": 52,
    "membership": "228",
    "name": "MR. RAJIV SHARMA & MRS . SONIA SHARMA",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 1,
    "email": null,
    "phone": "9868210374",
    "alternatePhone": null,
    "parking": "P-052",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 weeks ago",
    "committee": null,
    "vehicleNumber": "DL10CD 3490"
  },
  {
    "id": "EA-0053",
    "sn": 53,
    "flat": 53,
    "membership": "204",
    "name": "MR. S.K. TANWAR",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "sktanwar@outlook.com",
    "phone": "9818615075",
    "alternatePhone": null,
    "parking": "P-053",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL10CV 3352"
  },
  {
    "id": "EA-0054",
    "sn": 54,
    "flat": 54,
    "membership": "196",
    "name": "MR.RAVINDRA KUMAR VIJH",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "sudha.vijh@gmail.com",
    "phone": "9868139149/8287260959",
    "alternatePhone": null,
    "parking": "P-054",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "CH1CQ 8032"
  },
  {
    "id": "EA-0055",
    "sn": 55,
    "flat": 55,
    "membership": null,
    "name": "MR. SUDHANSHU MISRA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "sudhanshu26@gmail.com",
    "phone": "9911695263/9911058409",
    "alternatePhone": null,
    "parking": "P-055",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 weeks ago",
    "committee": null,
    "vehicleNumber": "HR26FM4624/ DL9CU 3975"
  },
  {
    "id": "EA-0056",
    "sn": 56,
    "flat": 56,
    "membership": "191",
    "name": "MRS. NEELAM BALA CHADHA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "8587090552",
    "alternatePhone": null,
    "parking": "P-056",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Yesterday",
    "committee": null,
    "vehicleNumber": "DL9CAN 2016"
  },
  {
    "id": "EA-0057",
    "sn": 57,
    "flat": 57,
    "membership": "221",
    "name": "MR. ANIL KAKKAR",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "ak_kr1953@rediffmail.com",
    "phone": "9811033156",
    "alternatePhone": null,
    "parking": "P-057",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL10CL 7453"
  },
  {
    "id": "EA-0058",
    "sn": 58,
    "flat": 58,
    "membership": "261",
    "name": "MR. ASHUTOSH NARANG",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "9953545569",
    "alternatePhone": "+91 97012• ••213",
    "parking": "P-058",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL8CBA 0181"
  },
  {
    "id": "EA-0059",
    "sn": 59,
    "flat": 59,
    "membership": "175",
    "name": "SMT. JALAJA SAJEEV AND SAJEEV V.S",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 1,
    "email": null,
    "phone": "9910993870",
    "alternatePhone": null,
    "parking": "P-059",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Yesterday",
    "committee": null,
    "vehicleNumber": "DL9CAZ 9122/DL12CU 7016"
  },
  {
    "id": "EA-0060",
    "sn": 60,
    "flat": 60,
    "membership": "102",
    "name": "MR. H.H. BHARDWAJ",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "hhbhardwaj05@gmail.com",
    "phone": "9871767856",
    "alternatePhone": null,
    "parking": "P-060",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAP3841"
  },
  {
    "id": "EA-0061",
    "sn": 61,
    "flat": 61,
    "membership": "404",
    "name": "DR. PAUL PARIAT",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "ericpariat@yahoo.com",
    "phone": "9810396558/9871102668",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL1CAA9081/DL10CW5121"
  },
  {
    "id": "EA-0062",
    "sn": 62,
    "flat": 62,
    "membership": "366",
    "name": "MRS. VANDANA SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "vandanasharma73@rediffmail.com",
    "phone": "9868369192/9968003372",
    "alternatePhone": null,
    "parking": "P-062",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Yesterday",
    "committee": null,
    "vehicleNumber": "DL9CAR 9983/ DL9CAU 4516"
  },
  {
    "id": "EA-0063",
    "sn": 63,
    "flat": 63,
    "membership": "305",
    "name": "MR. SANDEEP PUNJANI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "9011506876",
    "alternatePhone": null,
    "parking": "P-063",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "UP15DP4990"
  },
  {
    "id": "EA-0064",
    "sn": 64,
    "flat": 64,
    "membership": "392",
    "name": "MR. VIJAY RAM",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "9871567714",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL3CBA 6655"
  },
  {
    "id": "EA-0065",
    "sn": 65,
    "flat": 65,
    "membership": "387",
    "name": "MRS. MAYRA DAVID",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "mayradivid99@yahoo.com",
    "phone": "9312147017",
    "alternatePhone": null,
    "parking": "P-065",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Yesterday",
    "committee": null,
    "vehicleNumber": "DL14CE 8562"
  },
  {
    "id": "EA-0066",
    "sn": 66,
    "flat": 66,
    "membership": "396",
    "name": "MR. PRASHANT SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "9560573846",
    "alternatePhone": null,
    "parking": "P-066",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL3CCD1158"
  },
  {
    "id": "EA-0067",
    "sn": 67,
    "flat": 67,
    "membership": "280",
    "name": "MRS. R.K. CHADHA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "tarunmeetsinghhc@gmail.com",
    "phone": "9899296160",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "HR29AQ2033"
  },
  {
    "id": "EA-0068",
    "sn": 68,
    "flat": 68,
    "membership": "198",
    "name": "MRS.ANITA RATHORE",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "nishant.rathore1@gmail.com",
    "phone": "8826535514",
    "alternatePhone": null,
    "parking": "P-068",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Yesterday",
    "committee": null,
    "vehicleNumber": "DL12CS 6902/ DL10CW6526"
  },
  {
    "id": "EA-0069",
    "sn": 69,
    "flat": 69,
    "membership": "302",
    "name": "SMT. KIRAN MALIK",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "9899108885",
    "alternatePhone": null,
    "parking": "P-069",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL1CAD1527"
  },
  {
    "id": "EA-0070",
    "sn": 70,
    "flat": 70,
    "membership": "349",
    "name": "MRS. SUNITA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "madaan0005@gmail.com",
    "phone": "8130865699",
    "alternatePhone": null,
    "parking": "P-070",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "HR26DX 1296/DL7CW8576"
  },
  {
    "id": "EA-0071",
    "sn": 71,
    "flat": 71,
    "membership": "281",
    "name": "Mrs. ANITA SAXENA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "grace_7@rediffmail.com",
    "phone": "9968273735/9868950525",
    "alternatePhone": "+91 97015• ••216",
    "parking": "P-071",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Yesterday",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0072",
    "sn": 72,
    "flat": 72,
    "membership": "348",
    "name": "MR. ABHIMANYU LALL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "lallabhimanyu@gmail.com",
    "phone": "9910808880/9042476144",
    "alternatePhone": null,
    "parking": "P-072",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "1 week ago",
    "committee": null,
    "vehicleNumber": "HR12AM 7686 / HR12AS6300"
  },
  {
    "id": "EA-0073",
    "sn": 73,
    "flat": 73,
    "membership": "128",
    "name": "MR. KUNAL AGGARWAL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "kunalagg1983@gmail.com",
    "phone": "9871008307",
    "alternatePhone": null,
    "parking": "P-073",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL1CZ 6857"
  },
  {
    "id": "EA-0074",
    "sn": 74,
    "flat": 74,
    "membership": "395",
    "name": "MRS. SHASHI PRABHA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "9899885527",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0075",
    "sn": 75,
    "flat": 75,
    "membership": "389",
    "name": "MR. P.K. SAXENA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "prabhat2361@gmail.com",
    "phone": "9522566308/9868533819",
    "alternatePhone": null,
    "parking": "P-075",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "1 week ago",
    "committee": null,
    "vehicleNumber": "DL9CAY 7275"
  },
  {
    "id": "EA-0076",
    "sn": 76,
    "flat": 76,
    "membership": null,
    "name": "MR. PRAMOD KUMAR SINGH",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "kumarkashyap.amil@gmail.com",
    "phone": "7765882773/8130338318",
    "alternatePhone": null,
    "parking": "P-076",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAV 2228/JH01EQ 0019"
  },
  {
    "id": "EA-0077",
    "sn": 77,
    "flat": 77,
    "membership": "364",
    "name": "SMT. PUSHPALATA RAINA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "ajaykumarraina@gmail.com",
    "phone": "9873146020/9810629903",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "NEW TENANT ON  30/8/24"
  },
  {
    "id": "EA-0078",
    "sn": 78,
    "flat": 78,
    "membership": "53",
    "name": "MR. R.K. NARULA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "8860639870",
    "alternatePhone": null,
    "parking": "P-078",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "1 week ago",
    "committee": null,
    "vehicleNumber": "DL4CAD 6916"
  },
  {
    "id": "EA-0079",
    "sn": 79,
    "flat": 79,
    "membership": null,
    "name": "MR. RAGHVENDRA SACHAN & MRS. INDER PREET KAUR SACHAN",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 1,
    "email": "rvsachan@gmail.com",
    "phone": "9873989234",
    "alternatePhone": null,
    "parking": "P-079",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL10CQ 4508"
  },
  {
    "id": "EA-0080",
    "sn": 80,
    "flat": 80,
    "membership": "114",
    "name": "MR. SANJAY RAWAT",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "8376986842",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0081",
    "sn": 81,
    "flat": 81,
    "membership": "213",
    "name": "MR. S.C. VERMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "subashverma60@yahoo.com",
    "phone": "9910941566",
    "alternatePhone": null,
    "parking": "P-081",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "1 week ago",
    "committee": null,
    "vehicleNumber": "DL10CK 0482"
  },
  {
    "id": "EA-0082",
    "sn": 82,
    "flat": 82,
    "membership": null,
    "name": "MR. PANKAJ DUREJA & MRS. SHASHI",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 1,
    "email": null,
    "phone": "9811209758/9310718961",
    "alternatePhone": null,
    "parking": "P-082",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL10CW 2203"
  },
  {
    "id": "EA-0083",
    "sn": 83,
    "flat": 83,
    "membership": "237",
    "name": "MR. AJAY GANGULY",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": null,
    "phone": "7838217599",
    "alternatePhone": null,
    "parking": "P-083",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0084",
    "sn": 84,
    "flat": 84,
    "membership": "229",
    "name": "MR. C.D. SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 1,
    "email": "chanchaldsharma@hotmail.com",
    "phone": "9810383441",
    "alternatePhone": null,
    "parking": "P-084",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "1 week ago",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0085",
    "sn": 85,
    "flat": 85,
    "membership": "333",
    "name": "MR. R.B.S. UJLAN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "raviujlan@gmail.com",
    "phone": "9911495304/9718224975",
    "alternatePhone": null,
    "parking": "P-085",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "1 hr ago",
    "committee": null,
    "vehicleNumber": "DL9CX 9468/ DL3CBA 7447"
  },
  {
    "id": "EA-0086",
    "sn": 86,
    "flat": 86,
    "membership": "306",
    "name": "MR. K.P.C. RANA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "kpcrana24@gmail.com",
    "phone": "9868272990",
    "alternatePhone": null,
    "parking": "P-086",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0087",
    "sn": 87,
    "flat": 87,
    "membership": null,
    "name": "MRS. PREM LATA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "9873050879",
    "alternatePhone": null,
    "parking": "P-087",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAT 0354"
  },
  {
    "id": "EA-0088",
    "sn": 88,
    "flat": 88,
    "membership": "329",
    "name": "MR. B.J. SINGH",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "bjsk34@yahoo.com",
    "phone": "9818078383",
    "alternatePhone": null,
    "parking": "P-088",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "1 hr ago",
    "committee": null,
    "vehicleNumber": "DL10CW3422"
  },
  {
    "id": "EA-0089",
    "sn": 89,
    "flat": 89,
    "membership": "226",
    "name": "MRS. ALKA TIWARI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "ukdmcindia@gmail.com",
    "phone": "7542075233",
    "alternatePhone": null,
    "parking": "P-089",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CBB9249/JH01EF8287"
  },
  {
    "id": "EA-0090",
    "sn": 90,
    "flat": 90,
    "membership": "409",
    "name": "MR. YASH PAL BHATIA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "hsvirdhi@gmail.com",
    "phone": "9810309821",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "HR12AJ 2601/DL9CBG3349"
  },
  {
    "id": "EA-0091",
    "sn": 91,
    "flat": 91,
    "membership": "320",
    "name": "MS. USHA IYENGAR",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "55ushaing@gmail.com",
    "phone": "9650653854",
    "alternatePhone": null,
    "parking": "P-091",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "1 hr ago",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0092",
    "sn": 92,
    "flat": 92,
    "membership": "323",
    "name": "MR. V. NATARAJAN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "natrajan.ve@gmail.com",
    "phone": "9958893738",
    "alternatePhone": null,
    "parking": "P-092",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAP 7053"
  },
  {
    "id": "EA-0093",
    "sn": 93,
    "flat": 93,
    "membership": "411",
    "name": "MR. AJIT SHRIVASTAVA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "ajitsrivastava65@gmail.com",
    "phone": "9818003588",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAQ 5230"
  },
  {
    "id": "EA-0094",
    "sn": 94,
    "flat": 94,
    "membership": "27",
    "name": "MR. ASHOK MALHOTRA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "mmwpn@yahoo.com",
    "phone": "9818250466",
    "alternatePhone": null,
    "parking": "P-094",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "1 hr ago",
    "committee": null,
    "vehicleNumber": "GJ25A 1664"
  },
  {
    "id": "EA-0095",
    "sn": 95,
    "flat": 95,
    "membership": "322",
    "name": "MR. V.B. SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "sharmavb200@gmail.com",
    "phone": "9810449970",
    "alternatePhone": null,
    "parking": "P-095",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL4CBA 6297"
  },
  {
    "id": "EA-0096",
    "sn": 96,
    "flat": 96,
    "membership": "28",
    "name": "MR.T.RAMACHANDRAN & MRS. MINI RAMACHANDRAN",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 2,
    "email": "rama30568@yahoo.co.in",
    "phone": "9871196506/9717704457",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL8CAL 5247/ DL10CU 3188"
  },
  {
    "id": "EA-0097",
    "sn": 97,
    "flat": 97,
    "membership": "355",
    "name": "MR. DHARMENDRA PAL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "9811552206",
    "alternatePhone": null,
    "parking": "P-097",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "1 hr ago",
    "committee": null,
    "vehicleNumber": "DL9CAR 7128"
  },
  {
    "id": "EA-0098",
    "sn": 98,
    "flat": 98,
    "membership": "255",
    "name": "MR. R.S. SANDHU",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "9971370093",
    "alternatePhone": null,
    "parking": "P-098",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0099",
    "sn": 99,
    "flat": 99,
    "membership": "294",
    "name": "MS. SANTOSH KUMARI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "toshi.umang@gmail.com",
    "phone": "9871860464",
    "alternatePhone": null,
    "parking": "P-099",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": "Treasurer",
    "vehicleNumber": "DL2CAU 9995"
  },
  {
    "id": "EA-0100",
    "sn": 100,
    "flat": 100,
    "membership": "266",
    "name": "MR.NIKHIL CHADHA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "8527261112",
    "alternatePhone": "+91 97014• ••215",
    "parking": "P-100",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "1 hr ago",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0101",
    "sn": 101,
    "flat": 101,
    "membership": "403",
    "name": "MR. CHACKO EAPEN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "7042146177/9871495202",
    "alternatePhone": null,
    "parking": "P-101",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "4 days ago",
    "committee": null,
    "vehicleNumber": "DL9CAG 7591"
  },
  {
    "id": "EA-0102",
    "sn": 102,
    "flat": 102,
    "membership": "190",
    "name": "MR. P.S. TIWARI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "9968114395",
    "alternatePhone": null,
    "parking": "P-102",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CBE1805"
  },
  {
    "id": "EA-0103",
    "sn": 103,
    "flat": 103,
    "membership": "385",
    "name": "MR.Amit Gupta",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "guptaamit.amex@gmail.com",
    "phone": "9582338998",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL11CB 5059/ DL1CAG 1669"
  },
  {
    "id": "EA-0104",
    "sn": 104,
    "flat": 104,
    "membership": "384",
    "name": "MR.BIKRAM S RAWAT",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "bsrawat@abpresstech.com",
    "phone": "9810094476",
    "alternatePhone": null,
    "parking": "P-104",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "4 days ago",
    "committee": null,
    "vehicleNumber": "DL9CAY 7670/DL2CBC 5023"
  },
  {
    "id": "EA-0105",
    "sn": 105,
    "flat": 105,
    "membership": "414",
    "name": "MR.CHARU C MISHRA & MRS. NEERU MISHRA",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 2,
    "email": "ercchandra@gmail.com",
    "phone": "9852467023/8287092627",
    "alternatePhone": null,
    "parking": "P-105",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL8CY 2870"
  },
  {
    "id": "EA-0106",
    "sn": 106,
    "flat": 106,
    "membership": "388",
    "name": "MRS.RUPINDER GORAYA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "9810089821",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAY 4485"
  },
  {
    "id": "EA-0107",
    "sn": 107,
    "flat": 107,
    "membership": "406",
    "name": "MRS.NISHA, PARVEEN TYAGI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "abhinavtty@gmail.com",
    "phone": "8802777744/9911556344",
    "alternatePhone": null,
    "parking": "P-107",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "4 days ago",
    "committee": null,
    "vehicleNumber": "HR26DJ 7601/DL9CAZ 7867"
  },
  {
    "id": "EA-0108",
    "sn": 108,
    "flat": 108,
    "membership": "234",
    "name": "MR. BRAHM BHATIA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "9810386343",
    "alternatePhone": null,
    "parking": "P-108",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL1CP 9948"
  },
  {
    "id": "EA-0109",
    "sn": 109,
    "flat": 109,
    "membership": "400",
    "name": "MRS. SAPNA GARG",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "atulgargin@gmail.com",
    "phone": "9911362200/7982446228",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "TN39DY3700"
  },
  {
    "id": "EA-0110",
    "sn": 110,
    "flat": 110,
    "membership": "312",
    "name": "MRS. SANTOSH DARGAN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "9810029582",
    "alternatePhone": null,
    "parking": "P-110",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "4 days ago",
    "committee": null,
    "vehicleNumber": "DL4CAW 4868"
  },
  {
    "id": "EA-0111",
    "sn": 111,
    "flat": 111,
    "membership": "383",
    "name": "MR. SUNEET DARGAN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "suneetdargan@gmail.com",
    "phone": "9810029582",
    "alternatePhone": null,
    "parking": "P-111",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": "MC Member",
    "vehicleNumber": "DL3CCP 7329"
  },
  {
    "id": "EA-0112",
    "sn": 112,
    "flat": 112,
    "membership": "313",
    "name": "MRS. JYOTI DARGAN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "9818647917",
    "alternatePhone": null,
    "parking": "P-112",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL4CNA 4140"
  },
  {
    "id": "EA-0113",
    "sn": 113,
    "flat": 113,
    "membership": "254",
    "name": "MRS. SUDHA SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "sudhasharma9868@gmail.com",
    "phone": "9868105731/9868885731",
    "alternatePhone": null,
    "parking": "P-113",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "4 days ago",
    "committee": "Secretary",
    "vehicleNumber": "DL9CS 9739/DL2CAR 4771"
  },
  {
    "id": "EA-0114",
    "sn": 114,
    "flat": 114,
    "membership": "233",
    "name": "MR. SUNIL AGGARWAL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "sunilagarwal100@hotmail.com",
    "phone": "9540247389",
    "alternatePhone": null,
    "parking": "P-114",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": "DL9CAS 4195"
  },
  {
    "id": "EA-0115",
    "sn": 115,
    "flat": 115,
    "membership": null,
    "name": "LATE DHARAM VIR SHARMA",
    "deceased": true,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "9953628107",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Vacant",
    "status": "Deceased",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "UP14EN 8919"
  },
  {
    "id": "EA-0116",
    "sn": 116,
    "flat": 116,
    "membership": "326",
    "name": "MR. SOHAN SINGH & MR. MOHAN SINGH & MRS. PRITI RANA & MRS. HEM LATA",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 2,
    "email": "sohan83@gmail.com",
    "phone": "9811364473",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAT5245"
  },
  {
    "id": "EA-0117",
    "sn": 117,
    "flat": 117,
    "membership": "324",
    "name": "MR. RAJESH KUMAR YADAV & MRS. NEETA YADAV",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 2,
    "email": null,
    "phone": "9971100364",
    "alternatePhone": null,
    "parking": "P-117",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0118",
    "sn": 118,
    "flat": 118,
    "membership": "224",
    "name": "MRS. INDRA KADIAN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "7042166842",
    "alternatePhone": null,
    "parking": "P-118",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "CH01CG 3826/DL9CBC 7599"
  },
  {
    "id": "EA-0119",
    "sn": 119,
    "flat": 119,
    "membership": "195",
    "name": "MRS. SUDHA SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "sudhasharma254@yahoo.com",
    "phone": "8447018936",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL5CQ 2743"
  },
  {
    "id": "EA-0120",
    "sn": 120,
    "flat": 120,
    "membership": null,
    "name": "MRS. KRISHNAWANTI & MRS. ANITA GOSSAIN",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 2,
    "email": null,
    "phone": "9968265820",
    "alternatePhone": null,
    "parking": "P-120",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0121",
    "sn": 121,
    "flat": 121,
    "membership": "365",
    "name": "MR. JOHN.K. PHILIP",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "betsy.john6@gmail.com",
    "phone": "9810220772/9873097264",
    "alternatePhone": null,
    "parking": "P-121",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAL 6908/DL9CAE0156"
  },
  {
    "id": "EA-0122",
    "sn": 122,
    "flat": 122,
    "membership": null,
    "name": "MR. ANAND GOEL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "anand.goyal2@gmail.com",
    "phone": "9871143315",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL8CAT 1604"
  },
  {
    "id": "EA-0123",
    "sn": 123,
    "flat": 123,
    "membership": "407",
    "name": "MR. S.S. MAKHIJA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": null,
    "phone": "9811513815",
    "alternatePhone": null,
    "parking": "P-123",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": "DL10CU 0614 /DL 8CAQ 8881"
  },
  {
    "id": "EA-0124",
    "sn": 124,
    "flat": 124,
    "membership": "225",
    "name": "MS. JOAN R. BLAH",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "joan.blah@onttook.com",
    "phone": "8879881870",
    "alternatePhone": null,
    "parking": "P-124",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0125",
    "sn": 125,
    "flat": 125,
    "membership": null,
    "name": "MR. SANDEEP K. VERMA & MRS.MANJEET KAUR VERMA",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 2,
    "email": "sanverma82@gmail.com",
    "phone": "9891580725/9958508010",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CBC8214"
  },
  {
    "id": "EA-0126",
    "sn": 126,
    "flat": 126,
    "membership": "297",
    "name": "MR. V.K. SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 2,
    "email": "vinaymea@yahoo.com",
    "phone": "9958469669",
    "alternatePhone": null,
    "parking": "P-126",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": "HP36F9992"
  },
  {
    "id": "EA-0127",
    "sn": 127,
    "flat": 127,
    "membership": null,
    "name": "MS.SANDHYA KAKKAR",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "sandhykakkar@gmail.com",
    "phone": "9811441568/011-25756001",
    "alternatePhone": null,
    "parking": "P-127",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL14CF7419"
  },
  {
    "id": "EA-0128",
    "sn": 128,
    "flat": 128,
    "membership": "194",
    "name": "MS. RAKESH KIRAN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9868146537",
    "alternatePhone": null,
    "parking": "P-128",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0129",
    "sn": 129,
    "flat": 129,
    "membership": "293",
    "name": "MRS. DEEPA JAIN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "deep1962@gmail.com",
    "phone": "9990322179/9990334326",
    "alternatePhone": "+91 97013• ••214",
    "parking": "P-129",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Today",
    "committee": null,
    "vehicleNumber": "DL8CBG8401"
  },
  {
    "id": "EA-0130",
    "sn": 130,
    "flat": 130,
    "membership": "413",
    "name": "MRS. SUKLA CHAUHAN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "schauhan1176@gmail.com",
    "phone": "9868147053",
    "alternatePhone": null,
    "parking": "P-130",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 days ago",
    "committee": null,
    "vehicleNumber": "UP78DH 4256"
  },
  {
    "id": "EA-0131",
    "sn": 131,
    "flat": 131,
    "membership": "398",
    "name": "MR. PRAHLAD SINGH",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9871095803",
    "alternatePhone": null,
    "parking": "P-131",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL8CDC 2541/DL8CBE 2272"
  },
  {
    "id": "EA-0132",
    "sn": 132,
    "flat": 132,
    "membership": "417",
    "name": "SMT. USHA SURI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9810236171",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0133",
    "sn": 133,
    "flat": 133,
    "membership": "397",
    "name": "MR. SAURABH SHARMA & SMT. ANAMIKA SHARMA",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 3,
    "email": "suarabhsharma83@gmail.com",
    "phone": "9958097102",
    "alternatePhone": null,
    "parking": "P-133",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 days ago",
    "committee": "Vice President",
    "vehicleNumber": "DL2CAM8258"
  },
  {
    "id": "EA-0134",
    "sn": 134,
    "flat": 134,
    "membership": "211",
    "name": "MRS. RITA SUDAN",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "sidharthsudan@gmail.com",
    "phone": "9811288317",
    "alternatePhone": null,
    "parking": "P-134",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "HR26ED 2503"
  },
  {
    "id": "EA-0135",
    "sn": 135,
    "flat": 135,
    "membership": "373",
    "name": "MRS. KUSUM JOSHI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9891692656/9810327099",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "HR29AN 2656"
  },
  {
    "id": "EA-0136",
    "sn": 136,
    "flat": 136,
    "membership": "272",
    "name": "MRS. SHASHI SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "baldevrajsh@gmail.com",
    "phone": "9310046445/8851221347",
    "alternatePhone": null,
    "parking": "P-136",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 days ago",
    "committee": null,
    "vehicleNumber": "DL9CAS 6544"
  },
  {
    "id": "EA-0137",
    "sn": 137,
    "flat": 137,
    "membership": "343",
    "name": "MR. KUNAL KAPOOR AND MS. PRIYA KAPOOR",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 3,
    "email": null,
    "phone": "9650508253",
    "alternatePhone": null,
    "parking": "P-137",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL10CP2577"
  },
  {
    "id": "EA-0138",
    "sn": 138,
    "flat": 138,
    "membership": "206",
    "name": "MR. J.N. MOHANTY",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "jnm22@hotmail.com",
    "phone": "9899606446",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "GJ09BF 2708/DL11CE3751"
  },
  {
    "id": "EA-0139",
    "sn": 139,
    "flat": 139,
    "membership": "377",
    "name": "MR. OM PRAKASH JOSHI 7 MRS. HEMA JOSHI & MR. VIPUL JOSHI & MR. HARSHAL JOSHI",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 3,
    "email": "vipuljoshi6805@gmail.com",
    "phone": "8130884347",
    "alternatePhone": null,
    "parking": "P-139",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 days ago",
    "committee": null,
    "vehicleNumber": "DL9CAR 5146"
  },
  {
    "id": "EA-0140",
    "sn": 140,
    "flat": 140,
    "membership": "88",
    "name": "MR. O.P. DHAMIJA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "96436771213",
    "alternatePhone": null,
    "parking": "P-140",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0141",
    "sn": 141,
    "flat": 141,
    "membership": "296",
    "name": "MR. M.L. ARORA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "mlrora@yahoo.com",
    "phone": "9818003362",
    "alternatePhone": null,
    "parking": "P-141",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAT6564"
  },
  {
    "id": "EA-0142",
    "sn": 142,
    "flat": 142,
    "membership": "86",
    "name": "MR. BABURAM",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9871996544/9999729047",
    "alternatePhone": "+91 97016• ••217",
    "parking": "P-142",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 days ago",
    "committee": null,
    "vehicleNumber": "DL12CX3391"
  },
  {
    "id": "EA-0143",
    "sn": 143,
    "flat": 143,
    "membership": null,
    "name": "MRS. NIRMAL GUPTA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9582338998",
    "alternatePhone": null,
    "parking": "P-143",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 weeks ago",
    "committee": null,
    "vehicleNumber": "DL9CAS 3005"
  },
  {
    "id": "EA-0144",
    "sn": 144,
    "flat": 144,
    "membership": "278",
    "name": "MR. M.S. KAGRA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9717388399",
    "alternatePhone": null,
    "parking": "P-144",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9EV 0357"
  },
  {
    "id": "EA-0145",
    "sn": 145,
    "flat": 145,
    "membership": "166",
    "name": "MR. R.K. BHATIA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "ravinderbhatia2712@gmail.com",
    "phone": "9891234501",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL8CAV 4547"
  },
  {
    "id": "EA-0146",
    "sn": 146,
    "flat": 146,
    "membership": "184",
    "name": "MR. S.N. KHANNA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9910458218",
    "alternatePhone": null,
    "parking": "P-146",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 weeks ago",
    "committee": null,
    "vehicleNumber": "DL3CCW7084/DL4CAX7243"
  },
  {
    "id": "EA-0147",
    "sn": 147,
    "flat": 147,
    "membership": "368",
    "name": "MR. V.K. VERMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "viren2026@gmail.com",
    "phone": "9953559405/9818118661",
    "alternatePhone": null,
    "parking": "P-147",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL3CBV 8971/DL8CAT0354"
  },
  {
    "id": "EA-0148",
    "sn": 148,
    "flat": 148,
    "membership": "362",
    "name": "MR. R.K. DADHWAL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "rc_dadhwal@yahoo.co.in",
    "phone": "9873721048",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL3CBR2088/DL2CBB6867"
  },
  {
    "id": "EA-0149",
    "sn": 149,
    "flat": 149,
    "membership": "222",
    "name": "MRS. ANITA PATIAL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9891112660/9818691162",
    "alternatePhone": null,
    "parking": "P-149",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 weeks ago",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0150",
    "sn": 150,
    "flat": 150,
    "membership": "310",
    "name": "MRS. DAVINDER JEET KAUR",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9310102278/9312241313",
    "alternatePhone": null,
    "parking": "P-150",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAA 5379/DL8CAK 2459"
  },
  {
    "id": "EA-0151",
    "sn": 151,
    "flat": 151,
    "membership": "223",
    "name": "MR. R.K. PAL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "ratanpal@hotmail.com",
    "phone": "9650003140",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAE3029"
  },
  {
    "id": "EA-0152",
    "sn": 152,
    "flat": 152,
    "membership": "299",
    "name": "MRS. SUNAINA SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9868814837/9868814836",
    "alternatePhone": null,
    "parking": "P-152",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 weeks ago",
    "committee": null,
    "vehicleNumber": "DL 4CAQ 3252"
  },
  {
    "id": "EA-0153",
    "sn": 153,
    "flat": 153,
    "membership": "332",
    "name": "MRS. ASHA BANSAL",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "asbansal20@yahoo.com",
    "phone": "9873523357/9818277776",
    "alternatePhone": null,
    "parking": "P-153",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL12CH 5810"
  },
  {
    "id": "EA-0154",
    "sn": 154,
    "flat": 154,
    "membership": "11",
    "name": "MRS. MEENAKSHI IYER",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "meenakshi.b.iyer@gmail.com",
    "phone": "7678307662/9868830489",
    "alternatePhone": null,
    "parking": "P-154",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0155",
    "sn": 155,
    "flat": 155,
    "membership": "145",
    "name": "MR. K.G. MALHOTRA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "kamla2051@gmail.com",
    "phone": "9871593800/8327220464",
    "alternatePhone": null,
    "parking": "P-155",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "2 weeks ago",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0156",
    "sn": 156,
    "flat": 156,
    "membership": "327",
    "name": "MR. K.J. SINGH",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "kanwaldwarka17@gmail.com",
    "phone": "8527168949/7982087436",
    "alternatePhone": null,
    "parking": "P-156",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Yesterday",
    "committee": null,
    "vehicleNumber": "DL9CAL 7840"
  },
  {
    "id": "EA-0157",
    "sn": 157,
    "flat": 157,
    "membership": "205",
    "name": "MR. JUGAL KISHORE",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "jkgossain@gmail.com",
    "phone": "9968265820",
    "alternatePhone": null,
    "parking": "P-157",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": "President",
    "vehicleNumber": "DL7CL 5890"
  },
  {
    "id": "EA-0158",
    "sn": 158,
    "flat": 158,
    "membership": "367",
    "name": "MRS. ARUNA AHLAWAT",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9013291169",
    "alternatePhone": "+91 97012• ••213",
    "parking": "P-158",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL10CK 7270"
  },
  {
    "id": "EA-0159",
    "sn": 159,
    "flat": 159,
    "membership": "292",
    "name": "MR. KANDENNATH RAJIV & MRS K PREETA",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 3,
    "email": null,
    "phone": "8743017318",
    "alternatePhone": null,
    "parking": "P-159",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Yesterday",
    "committee": null,
    "vehicleNumber": null
  },
  {
    "id": "EA-0160",
    "sn": 160,
    "flat": 160,
    "membership": "295",
    "name": "MRS. M. MEGHNANI",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "8130225511/9818003362",
    "alternatePhone": null,
    "parking": "P-160",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "UP65AN 4632"
  },
  {
    "id": "EA-0161",
    "sn": 161,
    "flat": 161,
    "membership": "290",
    "name": "MRS. SAROJ BALA KAUSHIK & MRS,NIDHI KAUSHIK",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 3,
    "email": null,
    "phone": "8750626740",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL4CBC 5378 /DL1CW 5197"
  },
  {
    "id": "EA-0162",
    "sn": 162,
    "flat": 162,
    "membership": "380",
    "name": "MRS. A. PREMLATHA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "arul.rapob@gmail.com",
    "phone": "9818638637/9971694541",
    "alternatePhone": null,
    "parking": "P-162",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Yesterday",
    "committee": null,
    "vehicleNumber": "DL10CX6857"
  },
  {
    "id": "EA-0163",
    "sn": 163,
    "flat": 163,
    "membership": null,
    "name": "MR. RAJAN ARORA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": null,
    "phone": "9650909281/8104253426",
    "alternatePhone": null,
    "parking": "P-163",
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL1CX 6293/DL4CNA 6815"
  },
  {
    "id": "EA-0164",
    "sn": 164,
    "flat": 164,
    "membership": "369",
    "name": "MRS. LATA SHARMA",
    "deceased": false,
    "hasCoOwner": false,
    "floor": 3,
    "email": "microman26@rediffmail.com",
    "phone": "9811306309",
    "alternatePhone": null,
    "parking": null,
    "ownership": "Owner",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "—",
    "committee": null,
    "vehicleNumber": "DL9CAU 1659/ DL10CW7703"
  },
  {
    "id": "EA-0165",
    "sn": 165,
    "flat": 165,
    "membership": "179",
    "name": "MR. K.K. VERMA & MRS. APRAJITA SHARMA",
    "deceased": false,
    "hasCoOwner": true,
    "floor": 3,
    "email": "kishore1985verma@gmail.com",
    "phone": "9911336042/9868811804",
    "alternatePhone": null,
    "parking": "P-165",
    "ownership": "Owner (Joint)",
    "status": "Active",
    "login": "Enabled",
    "lastLogin": "Yesterday",
    "committee": null,
    "vehicleNumber": "DL9CY 3453"
  }
];

// Convenient lookups
const memberByFlat = (f) => MEMBERS.find(m => m.flat === f);

// Current "logged in" member: Saurabh Sharma (Flat 133)
const CURRENT_MEMBER = memberByFlat(133);

// Managing Committee derived from MEMBERS where committee field is set.
const COMMITTEE = MEMBERS.filter(m => m.committee).map(m => ({
  name: m.name,
  role: m.committee,
  flat: `Flat ${m.flat}`,
  term: "2024–2026",
  email: m.email,
  phone: m.phone,
}));

// Per-member completeness — counts which of the optional fields are present.
const REQUIRED_FIELDS = [
  { key: "email",         label: "Email" },
  { key: "phone",         label: "Phone" },
  { key: "membership",    label: "Membership No." },
  { key: "ownership",     label: "Occupancy" },
  { key: "parking",       label: "Parking" },
];
function memberCompleteness(m) {
  const missing = REQUIRED_FIELDS.filter(f => !m[f.key]).map(f => f.key);
  return {
    pct: Math.round(((REQUIRED_FIELDS.length - missing.length) / REQUIRED_FIELDS.length) * 100),
    missing,
  };
}

// Aggregate completion stats
const DATA_COMPLETION = {
  total: MEMBERS.length,
  byField: REQUIRED_FIELDS.map(f => ({
    key: f.key,
    label: f.label,
    filled: MEMBERS.filter(m => m[f.key]).length,
    missing: MEMBERS.filter(m => !m[f.key]).length,
  })),
  loginEnabled: MEMBERS.filter(m => m.login === "Enabled").length,
  loginPending: MEMBERS.filter(m => m.login === "Pending").length,
  loginNotInvited: MEMBERS.filter(m => m.login === "Not invited").length,
  noEmail: MEMBERS.filter(m => !m.email && !m.deceased).length,
  deceased: MEMBERS.filter(m => m.deceased).length,
  fullProfiles: MEMBERS.filter(m => memberCompleteness(m).missing.length === 0).length,
};

const NOTICES = [];

const EVENTS = [];

const DOCUMENTS = [];

const COMPLAINTS = [];

const ACTIVITY = [];

// Helpers
const fmtDate = (iso) => {
  const d = new Date(iso);
  return d.toLocaleDateString("en-IN", { day: "2-digit", month: "short" });
};

// Strip honorific prefixes (MR./MRS./MS./SMT./DR./LATE) and return a clean display name.
const personName = (n) => (n || "").replace(/^\s*(MR|MRS|MS|SMT|DR|LATE)\.?\s+/i, "").trim();

// First initial of name + first initial of second word, after stripping honorifics.
const personInitials = (n) => {
  const stripped = personName(n);
  const parts = stripped.split(/[\s.]+/).filter(Boolean);
  return ((parts[0] || "")[0] || "") + ((parts[1] || "")[0] || "");
};

// First given name only (handy for greetings).
const personFirstName = (n) => (personName(n).split(/[\s.]+/)[0] || "");

Object.assign(window, {
  SOCIETY, COMMITTEE, NOTICES, EVENTS, DOCUMENTS, MEMBERS, COMPLAINTS, ACTIVITY,
  CURRENT_MEMBER, fmtDate, REQUIRED_FIELDS, memberCompleteness, DATA_COMPLETION, memberByFlat,
  personName, personInitials, personFirstName,
});
