// data.jsx — Mock data for Evergreen Apartment prototype.
// 165 real members imported from MEMBERS LIST.docx. Most lack email/phone/parking
// — surfaced via the Data Completion admin module.

const SOCIETY = {
  name: "Evergreen Apartment",
  tagline: "A Cooperative Group Housing Society",
  est: "1998",
  location: "Plot 9, Sector 7, Dwarka, New Delhi — 110075",
  regNo: "Regd. No. 837",
  pan: "AAATE0837F",
  blocks: 1,
  flats: 165,
  floors: 4,
  area: "2.6 acres",
  email: "evergreensocietyplot9@gmail.com",
  phone: "011-42441492",
  domain: "evergreen-dwarka.in",
};

const MEMBERS = [
  { id: "EA-0001", sn: 1, flat: 1, membership: "176", name: "MR. P.S. Sharma", deceased: false, hasCoOwner: false, floor: 0, email: "p.s.sharma@gmail.com", phone: "+91 98042• ••144", alternatePhone: null, parking: "P-001", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "4 days ago", committee: null, vehicleNumber: "DL-13-WX-1050" },
  { id: "EA-0002", sn: 2, flat: 2, membership: null, name: "MRS. Madhu Bala Sharma", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: "P-002", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0003", sn: 3, flat: 3, membership: null, name: "MS. Shobha Singh", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0004", sn: 4, flat: 4, membership: null, name: "MR. J.K. Batra", deceased: false, hasCoOwner: false, floor: 0, email: "j.k.batra@gmail.com", phone: "+91 98035• ••137", alternatePhone: null, parking: "P-004", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "4 days ago", committee: null, vehicleNumber: "DL-12-PQ-1043" },
  { id: "EA-0005", sn: 5, flat: 5, membership: null, name: "MR. A.K. Singh", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: "P-005", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0006", sn: 6, flat: 6, membership: null, name: "SMT. Maya Devi", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0007", sn: 7, flat: 7, membership: "361", name: "MRS Sheela Devi", deceased: false, hasCoOwner: false, floor: 0, email: "mrs.sheela.devi@gmail.com", phone: "+91 98028• ••130", alternatePhone: null, parking: "P-007", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "4 days ago", committee: null, vehicleNumber: "DL-11-IJ-1036" },
  { id: "EA-0008", sn: 8, flat: 8, membership: "340", name: "MR. Kulwant Singh", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: "+91 98059• ••161", alternatePhone: null, parking: "P-008", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-12-NO-1067" },
  { id: "EA-0009", sn: 9, flat: 9, membership: "287", name: "MS. Komal Seal", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0010", sn: 10, flat: 10, membership: "378", name: "Smt.chander Kanta", deceased: false, hasCoOwner: false, floor: 0, email: "chander.kanta@gmail.com", phone: "+91 98021• ••123", alternatePhone: null, parking: "P-010", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "4 days ago", committee: null, vehicleNumber: "DL-10-BC-1029" },
  { id: "EA-0011", sn: 11, flat: 11, membership: "344", name: "SMT. Shivani Sabharwal", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: "+91 98052• ••154", alternatePhone: null, parking: "P-011", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-11-GH-1060" },
  { id: "EA-0012", sn: 12, flat: 12, membership: "298", name: "MR. Amar Singh Hada", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: "P-012", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0013", sn: 13, flat: 13, membership: "415", name: "Mr.naresh Kumar", deceased: false, hasCoOwner: false, floor: 0, email: "naresh.kumar@gmail.com", phone: "+91 98014• ••116", alternatePhone: null, parking: "P-013", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "4 days ago", committee: null, vehicleNumber: "DL-09-UV-1022" },
  { id: "EA-0014", sn: 14, flat: 14, membership: "375", name: "MR. H.M. Srivastava", deceased: false, hasCoOwner: false, floor: 0, email: "h.m.srivastava@gmail.com", phone: "+91 98045• ••147", alternatePhone: null, parking: "P-014", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-10-ZA-1053" },
  { id: "EA-0015", sn: 15, flat: 15, membership: "178", name: "MR. V. Chandramauli", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: "P-015", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0016", sn: 16, flat: 16, membership: "354", name: "MRS. R. Subramaniam", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0017", sn: 17, flat: 17, membership: "318", name: "MRS. Arun Lata Sharma", deceased: false, hasCoOwner: false, floor: 0, email: "arun.lata.sharma@gmail.com", phone: "+91 98038• ••140", alternatePhone: null, parking: "P-017", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-09-ST-1046" },
  { id: "EA-0018", sn: 18, flat: 18, membership: "342", name: "MR. J.K. Jain", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: "P-018", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0019", sn: 19, flat: 19, membership: "410", name: "MR. Santanu Saha", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0020", sn: 20, flat: 20, membership: "243", name: "MRS. Vandana Kohli", deceased: false, hasCoOwner: false, floor: 0, email: "vandana.kohli@gmail.com", phone: "+91 98031• ••133", alternatePhone: null, parking: "P-020", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-08-LM-1039" },
  { id: "EA-0021", sn: 21, flat: 21, membership: "393", name: "MRS Anupama Singh", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: "+91 98062• ••164", alternatePhone: null, parking: "P-021", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0022", sn: 22, flat: 22, membership: "390", name: "MR. Dori Lal & SMT Shashi Bala", deceased: false, hasCoOwner: true, floor: 0, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0023", sn: 23, flat: 23, membership: null, name: "MRS. Neelam Bala Chadha", deceased: false, hasCoOwner: false, floor: 0, email: "neelam.bala.chadha@gmail.com", phone: "+91 98024• ••126", alternatePhone: null, parking: "P-023", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-13-EF-1032" },
  { id: "EA-0024", sn: 24, flat: 24, membership: "370", name: "MRS. Sudha Karan", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: "+91 98055• ••157", alternatePhone: null, parking: "P-024", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-08-JK-1063" },
  { id: "EA-0025", sn: 25, flat: 25, membership: "391", name: "MR. Manish Negi", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0026", sn: 26, flat: 26, membership: "304", name: "MR. Anil Joshi", deceased: false, hasCoOwner: false, floor: 0, email: "anil.joshi@gmail.com", phone: "+91 98017• ••119", alternatePhone: null, parking: "P-026", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-12-XY-1025" },
  { id: "EA-0027", sn: 27, flat: 27, membership: null, name: "MR. Ashwani & MRS Rachna Chaudhary", deceased: false, hasCoOwner: true, floor: 0, email: null, phone: "+91 98048• ••150", alternatePhone: null, parking: "P-027", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-13-CD-1056" },
  { id: "EA-0028", sn: 28, flat: 28, membership: "334", name: "MR. Kuldip Singh", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: "P-028", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0029", sn: 29, flat: 29, membership: "182", name: "MR. Manish Jain & MRS. Sunita Jain", deceased: false, hasCoOwner: true, floor: 0, email: "manish.jain@gmail.com", phone: "+91 98010• ••112", alternatePhone: "+91 97013• ••214", parking: "P-029", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-11-QR-1018" },
  { id: "EA-0030", sn: 30, flat: 30, membership: null, name: "MR. S.K. Gupta", deceased: false, hasCoOwner: false, floor: 0, email: "s.k.gupta@gmail.com", phone: "+91 98041• ••143", alternatePhone: null, parking: "P-030", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 days ago", committee: null, vehicleNumber: "DL-12-VW-1049" },
  { id: "EA-0031", sn: 31, flat: 31, membership: "60", name: "MR. Rajesh Kaura & SMT Pooja Kaura", deceased: false, hasCoOwner: true, floor: 0, email: "rajesh.kaura@gmail.com", phone: "+91 98031• ••168", alternatePhone: null, parking: "P-031", ownership: "Owner", status: "Active", login: "Pending", lastLogin: "—", committee: "Vice-President", vehicleNumber: null },
  { id: "EA-0032", sn: 32, flat: 32, membership: "394", name: "Mr.vinod Kumar & Harpreet Kaur", deceased: false, hasCoOwner: true, floor: 0, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0033", sn: 33, flat: 33, membership: "308", name: "MRS. Umang Dawra", deceased: false, hasCoOwner: false, floor: 0, email: "umang.dawra@gmail.com", phone: "+91 98034• ••136", alternatePhone: null, parking: "P-033", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 days ago", committee: null, vehicleNumber: "DL-11-OP-1042" },
  { id: "EA-0034", sn: 34, flat: 34, membership: "321", name: "Mrs.suganthi Rajaram", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: "P-034", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0035", sn: 35, flat: 35, membership: "376", name: "MRS. M. Kaushik", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0036", sn: 36, flat: 36, membership: "170", name: "MR. Deepak Karan And Reema Karan", deceased: false, hasCoOwner: true, floor: 0, email: "deepak.karan.and.reema@gmail.com", phone: "+91 98027• ••129", alternatePhone: null, parking: "P-036", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 days ago", committee: null, vehicleNumber: "DL-10-HI-1035" },
  { id: "EA-0037", sn: 37, flat: 37, membership: "416", name: "SMT. Alka Sharma", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: "+91 98058• ••160", alternatePhone: null, parking: "P-037", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-11-MN-1066" },
  { id: "EA-0038", sn: 38, flat: 38, membership: "374", name: "MR Mukesh Khurana", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0039", sn: 39, flat: 39, membership: "235", name: "SMT. Saroj B Sharma", deceased: false, hasCoOwner: false, floor: 0, email: "saroj.b.sharma@gmail.com", phone: "+91 98020• ••122", alternatePhone: null, parking: "P-039", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 days ago", committee: null, vehicleNumber: "DL-09-AB-1028" },
  { id: "EA-0040", sn: 40, flat: 40, membership: null, name: "LATE Sandeep Bhardwaj", deceased: true, hasCoOwner: false, floor: 0, email: null, phone: "+91 98051• ••153", alternatePhone: null, parking: null, ownership: "Vacant / Deceased", status: "Deceased", login: "Disabled", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0041", sn: 41, flat: 41, membership: "208", name: "MR. S.K. Gupta", deceased: false, hasCoOwner: false, floor: 0, email: null, phone: null, alternatePhone: null, parking: "P-041", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0042", sn: 42, flat: 42, membership: "372", name: "MR. Bhanu Prakash", deceased: false, hasCoOwner: false, floor: 0, email: "bhanu.prakash@gmail.com", phone: "+91 98013• ••115", alternatePhone: "+91 97016• ••217", parking: "P-042", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 days ago", committee: null, vehicleNumber: "DL-08-TU-1021" },
  { id: "EA-0043", sn: 43, flat: 43, membership: "382", name: "MR. Naresh Bharadwaj", deceased: false, hasCoOwner: false, floor: 1, email: "naresh.bharadwaj@gmail.com", phone: "+91 98044• ••146", alternatePhone: null, parking: "P-043", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 weeks ago", committee: null, vehicleNumber: "DL-09-YZ-1052" },
  { id: "EA-0044", sn: 44, flat: 44, membership: "232", name: "Mr.gyanendar Singh Sirohi & MRS Saroj Sirohi", deceased: false, hasCoOwner: true, floor: 1, email: null, phone: null, alternatePhone: null, parking: "P-044", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0045", sn: 45, flat: 45, membership: null, name: "MRS. V. Muthuswamy", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0046", sn: 46, flat: 46, membership: "183", name: "Mrs.indu Chikara", deceased: false, hasCoOwner: false, floor: 1, email: "indu.chikara@gmail.com", phone: "+91 98037• ••139", alternatePhone: null, parking: "P-046", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 weeks ago", committee: null, vehicleNumber: "DL-08-RS-1045" },
  { id: "EA-0047", sn: 47, flat: 47, membership: "139", name: "MR. D.C. Rabha", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: "P-047", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0048", sn: 48, flat: 48, membership: "405", name: "MR. Rakesh Kumar Mrs.geeta Sharma", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0049", sn: 49, flat: 49, membership: null, name: "Mrs.anupama Sharma Andlokesh K Sharma", deceased: false, hasCoOwner: false, floor: 1, email: "anupama.sharma.andloke@gmail.com", phone: "+91 98030• ••132", alternatePhone: null, parking: "P-049", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 weeks ago", committee: null, vehicleNumber: "DL-13-KL-1038" },
  { id: "EA-0050", sn: 50, flat: 50, membership: "220", name: "MRS. Harinder Gill", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: "+91 98061• ••163", alternatePhone: null, parking: "P-050", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-08-PQ-1069" },
  { id: "EA-0051", sn: 51, flat: 51, membership: "300", name: "Late.r.k Sharma", deceased: true, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Vacant / Deceased", status: "Deceased", login: "Disabled", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0052", sn: 52, flat: 52, membership: "228", name: "MR. Rajiv Sharma And Soni Sharma", deceased: false, hasCoOwner: true, floor: 1, email: "rajiv.sharma.and.soni.@gmail.com", phone: "+91 98023• ••125", alternatePhone: null, parking: "P-052", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 weeks ago", committee: null, vehicleNumber: "DL-12-DE-1031" },
  { id: "EA-0053", sn: 53, flat: 53, membership: "204", name: "MR. S.K. Tanwar", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: "+91 98054• ••156", alternatePhone: null, parking: "P-053", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-13-IJ-1062" },
  { id: "EA-0054", sn: 54, flat: 54, membership: "196", name: "Mr.ravinder K Vijh", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: "P-054", ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0055", sn: 55, flat: 55, membership: null, name: "MR. Sudhanshu Misra", deceased: false, hasCoOwner: false, floor: 1, email: "sudhanshu.misra@gmail.com", phone: "+91 98016• ••118", alternatePhone: null, parking: "P-055", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 weeks ago", committee: null, vehicleNumber: "DL-11-WX-1024" },
  { id: "EA-0056", sn: 56, flat: 56, membership: "191", name: "Mrs.neelam Bala Chadha", deceased: false, hasCoOwner: false, floor: 1, email: "neelam.bala.chadha@gmail.com", phone: "+91 98047• ••149", alternatePhone: null, parking: "P-056", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Yesterday", committee: null, vehicleNumber: "DL-12-BC-1055" },
  { id: "EA-0057", sn: 57, flat: 57, membership: "221", name: "MR. Anil Kakkar", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: "P-057", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0058", sn: 58, flat: 58, membership: "261", name: "MR. Ashutosh Narang", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: "+91 98009• ••111", alternatePhone: "+91 97012• ••213", parking: "P-058", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-10-PQ-1017" },
  { id: "EA-0059", sn: 59, flat: 59, membership: "175", name: "SMT. Jalaja Sajeev & Sajeev V.s", deceased: false, hasCoOwner: true, floor: 1, email: "jalaja.sajeev@gmail.com", phone: "+91 98040• ••142", alternatePhone: null, parking: "P-059", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Yesterday", committee: null, vehicleNumber: "DL-11-UV-1048" },
  { id: "EA-0060", sn: 60, flat: 60, membership: "102", name: "MR. H.H. Bhardwaj", deceased: false, hasCoOwner: false, floor: 1, email: "h.h.bhardwaj@gmail.com", phone: "+91 98060• ••167", alternatePhone: null, parking: "P-060", ownership: "Owner", status: "Active", login: "Pending", lastLogin: "—", committee: "Member", vehicleNumber: null },
  { id: "EA-0061", sn: 61, flat: 61, membership: "404", name: "DR. Paul Pariat", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0062", sn: 62, flat: 62, membership: "366", name: "MRS. Vandana Sharma", deceased: false, hasCoOwner: false, floor: 1, email: "vandana.sharma@gmail.com", phone: "+91 98033• ••135", alternatePhone: null, parking: "P-062", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Yesterday", committee: null, vehicleNumber: "DL-10-NO-1041" },
  { id: "EA-0063", sn: 63, flat: 63, membership: "305", name: "MR. Sandeep Punjani", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: "P-063", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0064", sn: 64, flat: 64, membership: "392", name: "MR. Vijay Ram", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0065", sn: 65, flat: 65, membership: "387", name: "MRS. Mayra David", deceased: false, hasCoOwner: false, floor: 1, email: "mayra.david@gmail.com", phone: "+91 98026• ••128", alternatePhone: null, parking: "P-065", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Yesterday", committee: null, vehicleNumber: "DL-09-GH-1034" },
  { id: "EA-0066", sn: 66, flat: 66, membership: "396", name: "MR. Prashant Shama", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: "+91 98057• ••159", alternatePhone: null, parking: "P-066", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-10-LM-1065" },
  { id: "EA-0067", sn: 67, flat: 67, membership: "280", name: "MRS. R.K. Chadha", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0068", sn: 68, flat: 68, membership: "198", name: "Mrs.anita Rthore", deceased: false, hasCoOwner: false, floor: 1, email: "anita.rthore@gmail.com", phone: "+91 98019• ••121", alternatePhone: null, parking: "P-068", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Yesterday", committee: null, vehicleNumber: "DL-08-ZA-1027" },
  { id: "EA-0069", sn: 69, flat: 69, membership: "302", name: "MRS .kiran Malik", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: "+91 98050• ••152", alternatePhone: null, parking: "P-069", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-09-EF-1058" },
  { id: "EA-0070", sn: 70, flat: 70, membership: "349", name: "MRS. Sunita", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: "P-070", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0071", sn: 71, flat: 71, membership: "281", name: "MRS. Anita Saxena", deceased: false, hasCoOwner: false, floor: 1, email: "anita.saxena@gmail.com", phone: "+91 98012• ••114", alternatePhone: "+91 97015• ••216", parking: "P-071", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Yesterday", committee: null, vehicleNumber: "DL-13-ST-1020" },
  { id: "EA-0072", sn: 72, flat: 72, membership: "348", name: "MR. Abhimanyu Lall", deceased: false, hasCoOwner: false, floor: 1, email: "abhimanyu.lall@gmail.com", phone: "+91 98043• ••145", alternatePhone: null, parking: "P-072", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "1 week ago", committee: null, vehicleNumber: "DL-08-XY-1051" },
  { id: "EA-0073", sn: 73, flat: 73, membership: "128", name: "MR. Kunal Aggarwal", deceased: false, hasCoOwner: false, floor: 1, email: "kunal.aggarwal@gmail.com", phone: "+91 98073• ••170", alternatePhone: null, parking: "P-073", ownership: "Owner", status: "Active", login: "Pending", lastLogin: "—", committee: "Secretary", vehicleNumber: null },
  { id: "EA-0074", sn: 74, flat: 74, membership: "395", name: "MR. Vinay Mani Tripathi", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0075", sn: 75, flat: 75, membership: "389", name: "MR. P.K. Saxena", deceased: false, hasCoOwner: false, floor: 1, email: "p.k.saxena@gmail.com", phone: "+91 98036• ••138", alternatePhone: null, parking: "P-075", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "1 week ago", committee: null, vehicleNumber: "DL-13-QR-1044" },
  { id: "EA-0076", sn: 76, flat: 76, membership: null, name: "MR. Pramod Kumar Singh", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: "P-076", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0077", sn: 77, flat: 77, membership: "364", name: "MRS. Pushpalata Raina", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0078", sn: 78, flat: 78, membership: "53", name: "MR. R.K. Narula", deceased: false, hasCoOwner: false, floor: 1, email: "r.k.narula@gmail.com", phone: "+91 98029• ••131", alternatePhone: null, parking: "P-078", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "1 week ago", committee: null, vehicleNumber: "DL-12-JK-1037" },
  { id: "EA-0079", sn: 79, flat: 79, membership: null, name: "MR. Raghvendra Sachan & Mrs.inder Preet Kaur Sachan", deceased: false, hasCoOwner: true, floor: 1, email: null, phone: "+91 98060• ••162", alternatePhone: null, parking: "P-079", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-13-OP-1068" },
  { id: "EA-0080", sn: 80, flat: 80, membership: "114", name: "MR. Sanjay Rawat & MRS Benita Rawat", deceased: false, hasCoOwner: true, floor: 1, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0081", sn: 81, flat: 81, membership: "213", name: "MR. S.C. Verma", deceased: false, hasCoOwner: false, floor: 1, email: "s.c.verma@gmail.com", phone: "+91 98022• ••124", alternatePhone: null, parking: "P-081", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "1 week ago", committee: null, vehicleNumber: "DL-11-CD-1030" },
  { id: "EA-0082", sn: 82, flat: 82, membership: null, name: "MR. Pankaj Dureja & MRS. Shashi", deceased: false, hasCoOwner: true, floor: 1, email: null, phone: "+91 98053• ••155", alternatePhone: null, parking: "P-082", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-12-HI-1061" },
  { id: "EA-0083", sn: 83, flat: 83, membership: "237", name: "MR. Ajay Ganguly", deceased: false, hasCoOwner: false, floor: 1, email: null, phone: null, alternatePhone: null, parking: "P-083", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0084", sn: 84, flat: 84, membership: "229", name: "MR. C.D. Sharma", deceased: false, hasCoOwner: false, floor: 1, email: "c.d.sharma@gmail.com", phone: "+91 98015• ••117", alternatePhone: null, parking: "P-084", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "1 week ago", committee: null, vehicleNumber: "DL-10-VW-1023" },
  { id: "EA-0085", sn: 85, flat: 85, membership: "333", name: "MR. R.B.S. Ujlan", deceased: false, hasCoOwner: false, floor: 2, email: "r.b.s.ujlan@gmail.com", phone: "+91 98046• ••148", alternatePhone: null, parking: "P-085", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "1 hr ago", committee: null, vehicleNumber: "DL-11-AB-1054" },
  { id: "EA-0086", sn: 86, flat: 86, membership: "306", name: "MR. K.P.C. Rana", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: "P-086", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0087", sn: 87, flat: 87, membership: null, name: "MRS. Prem Lata", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: "P-087", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-09-OP-1016" },
  { id: "EA-0088", sn: 88, flat: 88, membership: "329", name: "MR. B.J. Singh", deceased: false, hasCoOwner: false, floor: 2, email: "b.j.singh@gmail.com", phone: "+91 98039• ••141", alternatePhone: null, parking: "P-088", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "1 hr ago", committee: null, vehicleNumber: "DL-10-TU-1047" },
  { id: "EA-0089", sn: 89, flat: 89, membership: "226", name: "Mrs.alka Tiwari", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: "P-089", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0090", sn: 90, flat: 90, membership: "409", name: "MR. Yash Pal Bhatia", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0091", sn: 91, flat: 91, membership: "320", name: "MS. Usha Iyengar", deceased: false, hasCoOwner: false, floor: 2, email: "usha.iyengar@gmail.com", phone: "+91 98032• ••134", alternatePhone: null, parking: "P-091", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "1 hr ago", committee: null, vehicleNumber: "DL-09-MN-1040" },
  { id: "EA-0092", sn: 92, flat: 92, membership: "323", name: "MR. V. Natarajan", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: "+91 98063• ••165", alternatePhone: null, parking: "P-092", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0093", sn: 93, flat: 93, membership: "411", name: "MR. Ajit Shrivastava", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0094", sn: 94, flat: 94, membership: "27", name: "MR. Ashok Malhotra", deceased: false, hasCoOwner: false, floor: 2, email: "ashok.malhotra@gmail.com", phone: "+91 98025• ••127", alternatePhone: null, parking: "P-094", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "1 hr ago", committee: null, vehicleNumber: "DL-08-FG-1033" },
  { id: "EA-0095", sn: 95, flat: 95, membership: "322", name: "MR. V.B. Sharma", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: "+91 98056• ••158", alternatePhone: null, parking: "P-095", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-09-KL-1064" },
  { id: "EA-0096", sn: 96, flat: 96, membership: "28", name: "Mr.t.ramachandran & MRS. Mini Ramachandran", deceased: false, hasCoOwner: true, floor: 2, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0097", sn: 97, flat: 97, membership: "355", name: "MR. Dharmendra Pal", deceased: false, hasCoOwner: false, floor: 2, email: "dharmendra.pal@gmail.com", phone: "+91 98018• ••120", alternatePhone: null, parking: "P-097", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "1 hr ago", committee: null, vehicleNumber: "DL-13-YZ-1026" },
  { id: "EA-0098", sn: 98, flat: 98, membership: "255", name: "MR. R.S. Sandhu", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: "+91 98049• ••151", alternatePhone: null, parking: "P-098", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-08-DE-1057" },
  { id: "EA-0099", sn: 99, flat: 99, membership: "294", name: "MS. Santosh Kumari", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: "P-099", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0100", sn: 100, flat: 100, membership: "266", name: "Mr.nikhil Chadha & SMT. Sakshi Kapoor", deceased: false, hasCoOwner: true, floor: 2, email: "nikhil.chadha@gmail.com", phone: "+91 98100• ••107", alternatePhone: "+91 97014• ••215", parking: "P-100", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "1 hr ago", committee: "Treasurer", vehicleNumber: "DL-12-RS-1019" },
  { id: "EA-0101", sn: 101, flat: 101, membership: "403", name: "MR. Chacko Eapen", deceased: false, hasCoOwner: false, floor: 2, email: "chacko.eapen@gmail.com", phone: "+91 98042• ••144", alternatePhone: null, parking: "P-101", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "4 days ago", committee: null, vehicleNumber: "DL-13-WX-1050" },
  { id: "EA-0102", sn: 102, flat: 102, membership: "190", name: "MR. P.S. Tiwari", deceased: false, hasCoOwner: false, floor: 2, email: "p.s.tiwari@gmail.com", phone: "+91 98102• ••169", alternatePhone: null, parking: "P-102", ownership: "Owner", status: "Active", login: "Pending", lastLogin: "—", committee: "Member", vehicleNumber: null },
  { id: "EA-0103", sn: 103, flat: 103, membership: "385", name: "MR.Amit Gupta", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0104", sn: 104, flat: 104, membership: "384", name: "Mr.bikram S Rawat & SMT. Beena Kumari", deceased: false, hasCoOwner: true, floor: 2, email: "bikram.s.rawat@gmail.com", phone: "+91 98035• ••137", alternatePhone: null, parking: "P-104", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "4 days ago", committee: null, vehicleNumber: "DL-12-PQ-1043" },
  { id: "EA-0105", sn: 105, flat: 105, membership: "414", name: "Mr.charu C Mishra & MRS. Neeru Mishra", deceased: false, hasCoOwner: true, floor: 2, email: null, phone: null, alternatePhone: null, parking: "P-105", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0106", sn: 106, flat: 106, membership: "388", name: "Mrs.rupinder Goraya", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0107", sn: 107, flat: 107, membership: "406", name: "Mrs.nisha, Parveen Tyagi", deceased: false, hasCoOwner: false, floor: 2, email: "nisha.parveen.tyagi@gmail.com", phone: "+91 98028• ••130", alternatePhone: null, parking: "P-107", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "4 days ago", committee: null, vehicleNumber: "DL-11-IJ-1036" },
  { id: "EA-0108", sn: 108, flat: 108, membership: "234", name: "MR. Brahm Bhatia", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: "+91 98059• ••161", alternatePhone: null, parking: "P-108", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-12-NO-1067" },
  { id: "EA-0109", sn: 109, flat: 109, membership: "400", name: "MRS. Sapna Garg", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0110", sn: 110, flat: 110, membership: "312", name: "MRS. Santosh Dargan", deceased: false, hasCoOwner: false, floor: 2, email: "santosh.dargan@gmail.com", phone: "+91 98021• ••123", alternatePhone: null, parking: "P-110", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "4 days ago", committee: null, vehicleNumber: "DL-10-BC-1029" },
  { id: "EA-0111", sn: 111, flat: 111, membership: "383", name: "MR. Suneet Dargan", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: "+91 98052• ••154", alternatePhone: null, parking: "P-111", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-11-GH-1060" },
  { id: "EA-0112", sn: 112, flat: 112, membership: "313", name: "MRS. Jyoti Dargan", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: "P-112", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0113", sn: 113, flat: 113, membership: "254", name: "MRS. Sudha Sharma", deceased: false, hasCoOwner: false, floor: 2, email: "sudha.sharma@gmail.com", phone: "+91 98014• ••116", alternatePhone: null, parking: "P-113", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "4 days ago", committee: null, vehicleNumber: "DL-09-UV-1022" },
  { id: "EA-0114", sn: 114, flat: 114, membership: "233", name: "MR. Sunil Aggarwal", deceased: false, hasCoOwner: false, floor: 2, email: "sunil.aggarwal@gmail.com", phone: "+91 98045• ••147", alternatePhone: null, parking: "P-114", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-10-ZA-1053" },
  { id: "EA-0115", sn: 115, flat: 115, membership: null, name: "LATE Dharam Vir Sharma", deceased: true, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Vacant / Deceased", status: "Deceased", login: "Disabled", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0116", sn: 116, flat: 116, membership: "326", name: "MR. Sohan Singh & MR. Mohan Singh & SMT. Priti Rana & SMT. Hem Lata", deceased: false, hasCoOwner: true, floor: 2, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0117", sn: 117, flat: 117, membership: "324", name: "MR. Rajesh Kumar Yadav And MRS. Neeta Yadav", deceased: false, hasCoOwner: true, floor: 2, email: "rajesh.kumar.yadav.and@gmail.com", phone: "+91 98038• ••140", alternatePhone: null, parking: "P-117", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-09-ST-1046" },
  { id: "EA-0118", sn: 118, flat: 118, membership: "224", name: "MRS. Indra Kadian", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: "P-118", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0119", sn: 119, flat: 119, membership: "195", name: "MRS. Sudha Sharma", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0120", sn: 120, flat: 120, membership: null, name: "MRS. Krishnawanti & MRS. Anita Gossain", deceased: false, hasCoOwner: true, floor: 2, email: "krishnawanti@gmail.com", phone: "+91 98031• ••133", alternatePhone: null, parking: "P-120", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-08-LM-1039" },
  { id: "EA-0121", sn: 121, flat: 121, membership: "365", name: "MR. John.k. Philip", deceased: false, hasCoOwner: false, floor: 2, email: "john.k.philip@gmail.com", phone: "+91 98121• ••158", alternatePhone: null, parking: "P-121", ownership: "Owner", status: "Active", login: "Pending", lastLogin: "—", committee: "Member", vehicleNumber: null },
  { id: "EA-0122", sn: 122, flat: 122, membership: null, name: "MR. Anand Goel", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0123", sn: 123, flat: 123, membership: "407", name: "MR. S.S. Makhija", deceased: false, hasCoOwner: false, floor: 2, email: "s.s.makhija@gmail.com", phone: "+91 98024• ••126", alternatePhone: null, parking: "P-123", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-13-EF-1032" },
  { id: "EA-0124", sn: 124, flat: 124, membership: "225", name: "MS. Joan Blah", deceased: false, hasCoOwner: false, floor: 2, email: null, phone: "+91 98055• ••157", alternatePhone: null, parking: "P-124", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-08-JK-1063" },
  { id: "EA-0125", sn: 125, flat: 125, membership: null, name: "MR. Sandeep K. Verma & SMT. Manjeet Kaur Verma", deceased: false, hasCoOwner: true, floor: 2, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0126", sn: 126, flat: 126, membership: "297", name: "MR. V.K. Sharma", deceased: false, hasCoOwner: false, floor: 2, email: "v.k.sharma@gmail.com", phone: "+91 98017• ••119", alternatePhone: null, parking: "P-126", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-12-XY-1025" },
  { id: "EA-0127", sn: 127, flat: 127, membership: null, name: "Ms.sandhya Kakkar", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: "+91 98048• ••150", alternatePhone: null, parking: "P-127", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-13-CD-1056" },
  { id: "EA-0128", sn: 128, flat: 128, membership: "194", name: "MS. Rakesh Kiran", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: "P-128", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0129", sn: 129, flat: 129, membership: "293", name: "MRS. Deepa Jain", deceased: false, hasCoOwner: false, floor: 3, email: "deepa.jain@gmail.com", phone: "+91 98010• ••112", alternatePhone: "+91 97013• ••214", parking: "P-129", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Today", committee: null, vehicleNumber: "DL-11-QR-1018" },
  { id: "EA-0130", sn: 130, flat: 130, membership: "413", name: "MRS. Sukla Chauhan", deceased: false, hasCoOwner: false, floor: 3, email: "sukla.chauhan@gmail.com", phone: "+91 98041• ••143", alternatePhone: null, parking: "P-130", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 days ago", committee: null, vehicleNumber: "DL-12-VW-1049" },
  { id: "EA-0131", sn: 131, flat: 131, membership: "398", name: "MR. Prahlad Singh", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: "P-131", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0132", sn: 132, flat: 132, membership: "417", name: "SMT. Usha Suri", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0133", sn: 133, flat: 133, membership: "397", name: "MR. Saurabh Sharma & SMT. Anamika Sharma", deceased: false, hasCoOwner: true, floor: 3, email: "saurabh.sharma@gmail.com", phone: "+91 98133• ••130", alternatePhone: null, parking: "P-133", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 days ago", committee: "President", vehicleNumber: "DL-11-OP-1042" },
  { id: "EA-0134", sn: 134, flat: 134, membership: "211", name: "MRS. Rita Sudan", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: "P-134", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0135", sn: 135, flat: 135, membership: "373", name: "MRS. Kusum Joshi", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0136", sn: 136, flat: 136, membership: "272", name: "MRS. Shashi Sharma", deceased: false, hasCoOwner: false, floor: 3, email: "shashi.sharma@gmail.com", phone: "+91 98027• ••129", alternatePhone: null, parking: "P-136", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 days ago", committee: null, vehicleNumber: "DL-10-HI-1035" },
  { id: "EA-0137", sn: 137, flat: 137, membership: "343", name: "MR. Kunal Kapoor Andpriya Kapoor", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: "+91 98058• ••160", alternatePhone: null, parking: "P-137", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-11-MN-1066" },
  { id: "EA-0138", sn: 138, flat: 138, membership: "206", name: "MR. J.N. Mohanty", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0139", sn: 139, flat: 139, membership: "377", name: "MR. OM Prakash Joshi & MRS Hema Joshi & MR Vipul Joshi & MR. Harshal Joshi", deceased: false, hasCoOwner: true, floor: 3, email: "om.prakash.joshi@gmail.com", phone: "+91 98020• ••122", alternatePhone: null, parking: "P-139", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 days ago", committee: null, vehicleNumber: "DL-09-AB-1028" },
  { id: "EA-0140", sn: 140, flat: 140, membership: "88", name: "MR. O.P. Dhamija", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: "+91 98051• ••153", alternatePhone: null, parking: "P-140", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-10-FG-1059" },
  { id: "EA-0141", sn: 141, flat: 141, membership: "296", name: "MR. M.L. Rora", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: "P-141", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0142", sn: 142, flat: 142, membership: "86", name: "MR. Baburam", deceased: false, hasCoOwner: false, floor: 3, email: "baburam@gmail.com", phone: "+91 98013• ••115", alternatePhone: "+91 97016• ••217", parking: "P-142", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 days ago", committee: null, vehicleNumber: "DL-08-TU-1021" },
  { id: "EA-0143", sn: 143, flat: 143, membership: null, name: "MRS. Nirmal Gupta", deceased: false, hasCoOwner: false, floor: 3, email: "nirmal.gupta@gmail.com", phone: "+91 98044• ••146", alternatePhone: null, parking: "P-143", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 weeks ago", committee: null, vehicleNumber: "DL-09-YZ-1052" },
  { id: "EA-0144", sn: 144, flat: 144, membership: "278", name: "MR. M.S. Kagra", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: "P-144", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0145", sn: 145, flat: 145, membership: "166", name: "MR. R.K. Bhatia", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0146", sn: 146, flat: 146, membership: "184", name: "MR. S.N. Khanna", deceased: false, hasCoOwner: false, floor: 3, email: "s.n.khanna@gmail.com", phone: "+91 98037• ••139", alternatePhone: null, parking: "P-146", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 weeks ago", committee: null, vehicleNumber: "DL-08-RS-1045" },
  { id: "EA-0147", sn: 147, flat: 147, membership: "368", name: "MR. V.K. Verma", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: "P-147", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0148", sn: 148, flat: 148, membership: "362", name: "MR. R.K. Dadhwal", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0149", sn: 149, flat: 149, membership: "222", name: "MRS. Anita Patial", deceased: false, hasCoOwner: false, floor: 3, email: "anita.patial@gmail.com", phone: "+91 98030• ••132", alternatePhone: null, parking: "P-149", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 weeks ago", committee: null, vehicleNumber: "DL-13-KL-1038" },
  { id: "EA-0150", sn: 150, flat: 150, membership: "310", name: "MRS. Davinder Jeet Kaur", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: "+91 98061• ••163", alternatePhone: null, parking: "P-150", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-08-PQ-1069" },
  { id: "EA-0151", sn: 151, flat: 151, membership: "223", name: "MR. R.K. Pal", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0152", sn: 152, flat: 152, membership: "299", name: "MRS. Sunaina Sharma", deceased: false, hasCoOwner: false, floor: 3, email: "sunaina.sharma@gmail.com", phone: "+91 98023• ••125", alternatePhone: null, parking: "P-152", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 weeks ago", committee: null, vehicleNumber: "DL-12-DE-1031" },
  { id: "EA-0153", sn: 153, flat: 153, membership: "332", name: "MRS. Asha Bansal", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: "+91 98054• ••156", alternatePhone: null, parking: "P-153", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-13-IJ-1062" },
  { id: "EA-0154", sn: 154, flat: 154, membership: "11", name: "MRS. Meenakshi Iyer", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: "P-154", ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0155", sn: 155, flat: 155, membership: "145", name: "MR. K.G. Malhotra", deceased: false, hasCoOwner: false, floor: 3, email: "k.g.malhotra@gmail.com", phone: "+91 98016• ••118", alternatePhone: null, parking: "P-155", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "2 weeks ago", committee: null, vehicleNumber: "DL-11-WX-1024" },
  { id: "EA-0156", sn: 156, flat: 156, membership: "327", name: "MR. K.J. Singh", deceased: false, hasCoOwner: false, floor: 3, email: "k.j.singh@gmail.com", phone: "+91 98047• ••149", alternatePhone: null, parking: "P-156", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Yesterday", committee: null, vehicleNumber: "DL-12-BC-1055" },
  { id: "EA-0157", sn: 157, flat: 157, membership: "205", name: "MR. Jugal Kishore", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: "P-157", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0158", sn: 158, flat: 158, membership: "367", name: "MRS. Aruna Ahlawat", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: "+91 98009• ••111", alternatePhone: "+91 97012• ••213", parking: "P-158", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: "DL-10-PQ-1017" },
  { id: "EA-0159", sn: 159, flat: 159, membership: "292", name: "Mr.kandengath Rajiv & MRS K. Preeta", deceased: false, hasCoOwner: true, floor: 3, email: "kandengath.rajiv@gmail.com", phone: "+91 98040• ••142", alternatePhone: null, parking: "P-159", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Yesterday", committee: null, vehicleNumber: "DL-11-UV-1048" },
  { id: "EA-0160", sn: 160, flat: 160, membership: "295", name: "MRS. M. Meghnani", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: "P-160", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0161", sn: 161, flat: 161, membership: "290", name: "MRS. Saroj Bala Kaushik & MRS Nidhi Kaushik", deceased: false, hasCoOwner: true, floor: 3, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Owner (Joint)", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0162", sn: 162, flat: 162, membership: "380", name: "MRS. A. Premlatha", deceased: false, hasCoOwner: false, floor: 3, email: "a.premlatha@gmail.com", phone: "+91 98033• ••135", alternatePhone: null, parking: "P-162", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Yesterday", committee: null, vehicleNumber: "DL-10-NO-1041" },
  { id: "EA-0163", sn: 163, flat: 163, membership: null, name: "MR. Rajan Arora", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: "P-163", ownership: "Owner", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0164", sn: 164, flat: 164, membership: "369", name: "MRS. Lata Sharma", deceased: false, hasCoOwner: false, floor: 3, email: null, phone: null, alternatePhone: null, parking: null, ownership: "Tenant", status: "Active", login: "No email", lastLogin: "—", committee: null, vehicleNumber: null },
  { id: "EA-0165", sn: 165, flat: 165, membership: "179", name: "MR. Kishore Kumar Verma & Mrs.aprajita Sharma", deceased: false, hasCoOwner: true, floor: 3, email: "kishore.kumar.verma@gmail.com", phone: "+91 98026• ••128", alternatePhone: null, parking: "P-165", ownership: "Owner", status: "Active", login: "Enabled", lastLogin: "Yesterday", committee: null, vehicleNumber: "DL-09-GH-1034" }
];

// Convenient lookups
const memberByFlat = (f) => MEMBERS.find(m => m.flat === f);

// Current "logged in" member: Saurabh Sharma (Flat 133)
const CURRENT_MEMBER = memberByFlat(133);

// Managing Committee derived from MEMBERS where committee field is set.
const COMMITTEE = MEMBERS.filter(m => m.committee).map(m => ({
  name: m.name,
  role: m.committee,
  flat: `Flat ${m.flat}`,
  term: "2024–2026",
  email: m.email,
  phone: m.phone,
}));

// Per-member completeness — counts which of the optional fields are present.
const REQUIRED_FIELDS = [
  { key: "email",         label: "Email" },
  { key: "phone",         label: "Phone" },
  { key: "membership",    label: "Membership No." },
  { key: "ownership",     label: "Occupancy" },
  { key: "parking",       label: "Parking" },
];
function memberCompleteness(m) {
  const missing = REQUIRED_FIELDS.filter(f => !m[f.key]).map(f => f.key);
  return {
    pct: Math.round(((REQUIRED_FIELDS.length - missing.length) / REQUIRED_FIELDS.length) * 100),
    missing,
  };
}

// Aggregate completion stats
const DATA_COMPLETION = {
  total: MEMBERS.length,
  byField: REQUIRED_FIELDS.map(f => ({
    key: f.key,
    label: f.label,
    filled: MEMBERS.filter(m => m[f.key]).length,
    missing: MEMBERS.filter(m => !m[f.key]).length,
  })),
  loginEnabled: MEMBERS.filter(m => m.login === "Enabled").length,
  loginPending: MEMBERS.filter(m => m.login === "Pending").length,
  loginNotInvited: MEMBERS.filter(m => m.login === "Not invited").length,
  noEmail: MEMBERS.filter(m => !m.email && !m.deceased).length,
  deceased: MEMBERS.filter(m => m.deceased).length,
  fullProfiles: MEMBERS.filter(m => memberCompleteness(m).missing.length === 0).length,
};

const NOTICES = [
  { id: "n-2026-018", date: "May 22, 2026", title: "Notice of 28th Annual General Meeting",            cat: "AGM",         pinned: true,  vis: "members", body: "The 28th AGM of Evergreen Apartment CGHS Ltd. will be held on Saturday, 12 July 2026 at 5:00 PM in the Community Hall." },
  { id: "n-2026-017", date: "May 18, 2026", title: "Quarterly Maintenance Bill — Q2 FY 2026-27",       cat: "Payment",     pinned: false, vis: "members", body: "Bills for Apr–Jun 2026 dispatched. Due date: 10 June 2026. Late fee 2% per month thereafter." },
  { id: "n-2026-016", date: "May 14, 2026", title: "Lift Modernisation — Floors 1-5",                  cat: "Maintenance", pinned: false, vis: "public",  body: "Phase-1 modernisation of lifts begins 02 June. Single lift operational throughout work hours." },
  { id: "n-2026-015", date: "May 9, 2026",  title: "Water Tank Cleaning Schedule",                     cat: "Maintenance", pinned: false, vis: "public",  body: "Underground and overhead tanks to be cleaned during 28–30 May. Brief 4-hr shutdowns; refer schedule." },
  { id: "n-2026-014", date: "May 2, 2026",  title: "Election of Managing Committee — Nominations Open",cat: "Election",    pinned: false, vis: "members", body: "Nominations for the 2026–2028 Managing Committee invited until 18 June. Forms available at the Society Office." },
  { id: "n-2026-013", date: "Apr 28, 2026", title: "Statutory Audit Report FY 2024-25 — Filed",        cat: "Compliance",  pinned: false, vis: "members", body: "Audit report for FY 2024-25 has been filed with the Office of RCS. Members may review the report in the document library." },
  { id: "n-2026-012", date: "Apr 21, 2026", title: "Independence Day Celebration — Save the date",     cat: "Notice",      pinned: false, vis: "public",  body: "Flag hoisting and community breakfast on 15 August at 8:00 AM at the central lawn. All residents and families welcome." },
];

const EVENTS = [
  { id: "e1", date: "2026-06-02", time: "09:00", title: "Lift Modernisation — Phase 1 begins", cat: "Maintenance",   vis: "members", loc: "Main building", docs: 2 },
  { id: "e2", date: "2026-06-05", time: "10:00", title: "Water tank cleaning",                cat: "Maintenance",   vis: "members", loc: "Roof + basement", docs: 1 },
  { id: "e3", date: "2026-06-10", time: "23:59", title: "Q2 Maintenance dues — Last date",    cat: "Payment",       vis: "members", loc: "Society Office",  docs: 1 },
  { id: "e4", date: "2026-06-15", time: "18:30", title: "MC Meeting — June",                  cat: "MC Meeting",    vis: "members", loc: "Society Office",  docs: 3 },
  { id: "e5", date: "2026-06-18", time: "17:00", title: "Election nominations close",         cat: "Election",      vis: "members", loc: "Society Office",  docs: 2 },
  { id: "e6", date: "2026-08-15", time: "08:00", title: "Independence Day flag hoisting",     cat: "Society Event", vis: "public",  loc: "Central Lawn",    docs: 0 },
  { id: "e7", date: "2026-07-12", time: "17:00", title: "28th Annual General Meeting",        cat: "AGM",           vis: "members", loc: "Community Hall",  docs: 6 },
  { id: "e8", date: "2026-07-20", time: "10:00", title: "MC Election Day",                    cat: "Election",      vis: "members", loc: "Community Hall",  docs: 4 },
];

const DOCUMENTS = [
  { id: "d1",  title: "AGM Notice — 28th AGM",              cat: "AGM",        size: "412 KB", date: "May 22, 2026",  ver: "v1", vis: "members", uploadedBy: "Kunal Aggarwal", linkedEvent: "e7" },
  { id: "d2",  title: "Agenda — 28th AGM",                  cat: "AGM",        size: "238 KB", date: "May 22, 2026",  ver: "v1", vis: "members", uploadedBy: "Kunal Aggarwal", linkedEvent: "e7" },
  { id: "d3",  title: "Minutes of 27th AGM (Jul 2025)",     cat: "AGM",        size: "1.1 MB", date: "Aug 04, 2025",  ver: "v2", vis: "members", uploadedBy: "Kunal Aggarwal" },
  { id: "d4",  title: "Statutory Audit Report FY 2024-25",  cat: "Audit",      size: "3.4 MB", date: "Apr 28, 2026",  ver: "v1", vis: "members", uploadedBy: "Nikhil Chadha" },
  { id: "d5",  title: "Annual Return FY 2024-25",           cat: "Annual",     size: "1.8 MB", date: "Apr 28, 2026",  ver: "v1", vis: "members", uploadedBy: "Nikhil Chadha" },
  { id: "d6",  title: "MC Resolution — Lift Modernisation", cat: "MC",         size: "186 KB", date: "Apr 12, 2026",  ver: "v1", vis: "members", uploadedBy: "Kunal Aggarwal", linkedEvent: "e1" },
  { id: "d7",  title: "Election Notice — 2026 MC Polls",    cat: "Election",   size: "318 KB", date: "May 02, 2026",  ver: "v1", vis: "members", uploadedBy: "Kunal Aggarwal", linkedEvent: "e8" },
  { id: "d8",  title: "Nomination Form (Form-A)",           cat: "Form",       size: "94 KB",  date: "May 02, 2026",  ver: "v1", vis: "public",  uploadedBy: "Kunal Aggarwal" },
  { id: "d9",  title: "Bye-laws — Evergreen CGHS",          cat: "Bye-laws",   size: "2.2 MB", date: "Jan 15, 2023",  ver: "v3", vis: "public",  uploadedBy: "Kunal Aggarwal" },
  { id: "d10", title: "Maintenance Vendor Schedule — Jun 2026", cat: "Maintenance", size: "210 KB", date: "May 14, 2026", ver: "v1", vis: "members", uploadedBy: "H.H. Bhardwaj", linkedEvent: "e1" },
  { id: "d11", title: "RCS Compliance Certificate 2025",    cat: "Compliance", size: "604 KB", date: "Mar 04, 2026",  ver: "v1", vis: "public",  uploadedBy: "Kunal Aggarwal" },
  { id: "d12", title: "Parking Allocation Master List",     cat: "Parking",    size: "1.2 MB", date: "Feb 22, 2026",  ver: "v4", vis: "admin",   uploadedBy: "H.H. Bhardwaj" },
  { id: "d13", title: "Society Registration Certificate",   cat: "Bye-laws",   size: "488 KB", date: "Aug 21, 1998",  ver: "v1", vis: "public",  uploadedBy: "Society Office" },
];

const COMPLAINTS = [
  { id: "EA-CMP-2026-041", date: "May 21, 2026", title: "Water seepage on ceiling",                cat: "Maintenance", status: "In Progress", by: "Mrs. Madhu Bala Sharma", flat: 2,   assignee: "Maintenance Vendor", priority: "High" },
  { id: "EA-CMP-2026-040", date: "May 20, 2026", title: "Gate intercom not working",               cat: "Security",    status: "Open",        by: "Mr. R.K. Narula",        flat: 78,  assignee: "Unassigned",         priority: "Medium" },
  { id: "EA-CMP-2026-039", date: "May 16, 2026", title: "Lawn lights stay on during day",          cat: "Maintenance", status: "Resolved",    by: "Mr. Kunal Aggarwal",     flat: 73,  assignee: "Electrician",        priority: "Low" },
  { id: "EA-CMP-2026-038", date: "May 12, 2026", title: "Lift makes scraping sound on 4th floor",  cat: "Maintenance", status: "In Progress", by: "Mr. Saurabh Sharma",     flat: 133, assignee: "Lift Vendor",        priority: "High" },
  { id: "EA-CMP-2026-037", date: "May 08, 2026", title: "Request: visitor parking near gate-2",    cat: "Parking",     status: "Open",        by: "Mr. P.S. Sharma",        flat: 1,   assignee: "Unassigned",         priority: "Low" },
  { id: "EA-CMP-2026-036", date: "May 03, 2026", title: "Stair light bulb fused — 3rd floor",      cat: "Maintenance", status: "Resolved",    by: "Mrs. Rita Sudan",        flat: 134, assignee: "Electrician",        priority: "Medium" },
];

const ACTIVITY = [
  { t: "10:42 AM", who: "Kunal Aggarwal", action: "Published notice",       target: "Notice of 28th AGM" },
  { t: "10:38 AM", who: "Kunal Aggarwal", action: "Attached document",      target: "AGM Notice → Event e7" },
  { t: "10:31 AM", who: "Nikhil Chadha",  action: "Uploaded document",      target: "Statutory Audit Report FY 2024-25" },
  { t: "10:30 AM", who: "Nikhil Chadha",  action: "Set visibility",         target: "Audit Report → Members-only" },
  { t: "09:14 AM", who: "Saurabh Sharma", action: "Updated member",         target: "Flat 41 — added phone & email" },
  { t: "09:08 AM", who: "Saurabh Sharma", action: "Sent invitation",        target: "Flat 41 — login invite" },
  { t: "Yesterday",who: "Saurabh Sharma", action: "Sent reminders",         target: "AGM — 7 day reminder (165 recipients)" },
  { t: "Yesterday",who: "H.H. Bhardwaj",  action: "Bulk import",            target: "12 members updated with phone numbers" },
  { t: "May 21",   who: "System",         action: "Login invitations sent", target: "Batch — 14 members" },
  { t: "May 20",   who: "Kunal Aggarwal", action: "Created event",          target: "Lift Modernisation Phase 1" },
];

// Helpers
const fmtDate = (iso) => {
  const d = new Date(iso);
  return d.toLocaleDateString("en-IN", { day: "2-digit", month: "short" });
};

// Strip honorific prefixes (MR./MRS./MS./SMT./DR./LATE) and return a clean display name.
const personName = (n) => (n || "").replace(/^\s*(MR|MRS|MS|SMT|DR|LATE)\.?\s+/i, "").trim();

// First initial of name + first initial of second word, after stripping honorifics.
const personInitials = (n) => {
  const stripped = personName(n);
  const parts = stripped.split(/[\s.]+/).filter(Boolean);
  return ((parts[0] || "")[0] || "") + ((parts[1] || "")[0] || "");
};

// First given name only (handy for greetings).
const personFirstName = (n) => (personName(n).split(/[\s.]+/)[0] || "");

Object.assign(window, {
  SOCIETY, COMMITTEE, NOTICES, EVENTS, DOCUMENTS, MEMBERS, COMPLAINTS, ACTIVITY,
  CURRENT_MEMBER, fmtDate, REQUIRED_FIELDS, memberCompleteness, DATA_COMPLETION, memberByFlat,
  personName, personInitials, personFirstName,
});
